// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_simple_0_0_1 (
        ap_clk,
        ap_rst,
        data_0_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] data_0_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [15:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [15:0] ap_return_29;
output  [15:0] ap_return_30;
output  [15:0] ap_return_31;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;
reg[15:0] ap_return_7;
reg[15:0] ap_return_8;
reg[15:0] ap_return_9;
reg[15:0] ap_return_10;
reg[15:0] ap_return_11;
reg[15:0] ap_return_12;
reg[15:0] ap_return_13;
reg[15:0] ap_return_14;
reg[15:0] ap_return_15;
reg[15:0] ap_return_16;
reg[15:0] ap_return_17;
reg[15:0] ap_return_18;
reg[15:0] ap_return_19;
reg[15:0] ap_return_20;
reg[15:0] ap_return_21;
reg[15:0] ap_return_22;
reg[15:0] ap_return_23;
reg[15:0] ap_return_24;
reg[15:0] ap_return_25;
reg[15:0] ap_return_26;
reg[15:0] ap_return_27;
reg[15:0] ap_return_28;
reg[15:0] ap_return_29;
reg[15:0] ap_return_30;
reg[15:0] ap_return_31;

reg  signed [15:0] data_0_V_read_8_reg_4913;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [12:0] trunc_ln_reg_4922;
reg   [15:0] trunc_ln708_1_reg_4927;
reg   [15:0] trunc_ln708_2_reg_4932;
reg   [14:0] trunc_ln708_s_reg_4937;
reg   [14:0] trunc_ln708_22_reg_4942;
reg   [15:0] trunc_ln708_5_reg_4947;
reg   [11:0] trunc_ln708_23_reg_4952;
reg   [14:0] trunc_ln708_29_reg_4957;
reg   [15:0] trunc_ln708_8_reg_4962;
reg   [15:0] trunc_ln708_9_reg_4967;
reg   [15:0] trunc_ln708_10_reg_4972;
reg   [13:0] trunc_ln708_30_reg_4977;
reg   [15:0] trunc_ln708_12_reg_4982;
reg   [15:0] trunc_ln708_14_reg_4987;
reg   [14:0] trunc_ln708_33_reg_4992;
reg   [14:0] trunc_ln708_34_reg_4997;
reg   [14:0] trunc_ln708_35_reg_5002;
reg   [15:0] trunc_ln708_18_reg_5007;
reg   [15:0] trunc_ln708_19_reg_5012;
reg   [15:0] trunc_ln708_20_reg_5017;
reg   [15:0] trunc_ln708_21_reg_5022;
reg   [11:0] trunc_ln708_36_reg_5027;
reg   [15:0] trunc_ln708_24_reg_5032;
reg   [15:0] trunc_ln708_25_reg_5037;
reg   [15:0] trunc_ln708_26_reg_5042;
reg   [15:0] trunc_ln708_27_reg_5047;
reg   [15:0] trunc_ln708_28_reg_5052;
reg   [12:0] trunc_ln708_38_reg_5057;
reg   [15:0] trunc_ln708_31_reg_5062;
wire  signed [15:0] mul_ln1118_58_fu_206_p0;
wire  signed [25:0] sext_ln1116_cast1_fu_4039_p1;
wire    ap_block_pp0_stage0;
wire  signed [15:0] mul_ln1118_45_fu_208_p0;
wire  signed [24:0] sext_ln1116_cast2_fu_4029_p1;
wire  signed [15:0] mul_ln1118_48_fu_209_p0;
wire  signed [15:0] mul_ln1118_51_fu_210_p0;
wire  signed [15:0] mul_ln1118_40_fu_211_p0;
wire  signed [15:0] mul_ln1118_fu_214_p0;
wire  signed [22:0] sext_ln1116_cast_fu_4061_p1;
wire  signed [15:0] mul_ln1118_60_fu_215_p0;
wire  signed [15:0] mul_ln1118_63_fu_216_p0;
wire  signed [15:0] mul_ln1118_49_fu_217_p0;
wire  signed [15:0] mul_ln1118_64_fu_219_p0;
wire  signed [15:0] mul_ln1118_43_fu_220_p0;
wire  signed [15:0] mul_ln1118_46_fu_221_p0;
wire  signed [15:0] mul_ln1118_56_fu_222_p0;
wire  signed [15:0] mul_ln1118_54_fu_223_p0;
wire  signed [15:0] mul_ln1118_47_fu_224_p0;
wire  signed [15:0] mul_ln1118_52_fu_225_p0;
wire  signed [15:0] mul_ln1118_41_fu_226_p0;
wire  signed [15:0] mul_ln1118_50_fu_227_p0;
wire  signed [15:0] mul_ln1118_44_fu_228_p0;
wire  signed [15:0] mul_ln1118_42_fu_229_p0;
wire  signed [15:0] mul_ln1118_57_fu_230_p0;
wire  signed [15:0] mul_ln1118_65_fu_231_p0;
wire  signed [15:0] mul_ln1118_39_fu_232_p0;
wire  signed [15:0] mul_ln1118_61_fu_233_p0;
wire  signed [15:0] mul_ln1118_53_fu_234_p0;
wire  signed [15:0] mul_ln1118_59_fu_235_p0;
wire  signed [15:0] mul_ln1118_55_fu_236_p0;
wire  signed [15:0] mul_ln1118_62_fu_237_p0;
wire  signed [15:0] sext_ln1116_cast4_fu_4019_p0;
wire  signed [15:0] sext_ln1116_cast3_fu_4024_p0;
wire  signed [15:0] sext_ln1116_cast2_fu_4029_p0;
wire  signed [15:0] sext_ln1116_cast1_fu_4039_p0;
wire  signed [15:0] sext_ln1116_cast_fu_4061_p0;
wire   [22:0] mul_ln1118_fu_214_p2;
wire   [25:0] mul_ln1118_39_fu_232_p2;
wire   [25:0] mul_ln1118_40_fu_211_p2;
wire   [24:0] mul_ln1118_41_fu_226_p2;
wire   [24:0] mul_ln1118_42_fu_229_p2;
wire   [25:0] mul_ln1118_43_fu_220_p2;
wire   [21:0] mul_ln1118_44_fu_228_p2;
wire   [24:0] mul_ln1118_45_fu_208_p2;
wire   [25:0] mul_ln1118_46_fu_221_p2;
wire   [25:0] mul_ln1118_47_fu_224_p2;
wire   [25:0] mul_ln1118_48_fu_209_p2;
wire   [23:0] mul_ln1118_49_fu_217_p2;
wire   [25:0] mul_ln1118_50_fu_227_p2;
wire   [25:0] mul_ln1118_51_fu_210_p2;
wire   [24:0] mul_ln1118_52_fu_225_p2;
wire   [24:0] mul_ln1118_53_fu_234_p2;
wire   [24:0] mul_ln1118_54_fu_223_p2;
wire   [25:0] mul_ln1118_55_fu_236_p2;
wire   [25:0] mul_ln1118_56_fu_222_p2;
wire   [25:0] mul_ln1118_57_fu_230_p2;
wire   [25:0] mul_ln1118_58_fu_206_p2;
wire  signed [15:0] trunc_ln708_36_fu_4277_p1;
wire   [25:0] mul_ln1118_59_fu_235_p2;
wire   [25:0] mul_ln1118_60_fu_215_p2;
wire   [25:0] mul_ln1118_61_fu_233_p2;
wire   [25:0] mul_ln1118_62_fu_237_p2;
wire   [25:0] mul_ln1118_63_fu_216_p2;
wire   [22:0] mul_ln1118_64_fu_219_p2;
wire   [25:0] mul_ln1118_65_fu_231_p2;
wire  signed [19:0] shl_ln_fu_4375_p3;
wire   [16:0] shl_ln1118_s_fu_4386_p3;
wire  signed [20:0] sext_ln1118_43_fu_4393_p1;
wire  signed [20:0] sext_ln1118_42_fu_4382_p1;
wire   [20:0] sub_ln1118_fu_4397_p2;
wire   [10:0] trunc_ln708_32_fu_4403_p4;
wire   [21:0] shl_ln1118_70_fu_4426_p3;
wire  signed [22:0] sext_ln1118_45_fu_4433_p1;
wire   [22:0] sub_ln1118_1_fu_4437_p2;
wire  signed [22:0] sext_ln1118_46_fu_4443_p1;
wire   [22:0] sub_ln1118_2_fu_4447_p2;
wire   [12:0] tmp_fu_4453_p4;
wire   [22:0] shl_ln1118_71_fu_4470_p3;
wire   [18:0] shl_ln1118_72_fu_4481_p3;
wire  signed [23:0] sext_ln1118_48_fu_4477_p1;
wire  signed [23:0] sext_ln1118_49_fu_4488_p1;
wire   [23:0] sub_ln1118_3_fu_4492_p2;
wire   [13:0] trunc_ln708_37_fu_4498_p4;
wire  signed [13:0] sext_ln1118_fu_4357_p1;
wire   [13:0] add_ln703_fu_4515_p2;
wire  signed [15:0] sext_ln708_fu_4360_p1;
wire  signed [15:0] sext_ln708_3_fu_4363_p1;
wire  signed [12:0] sext_ln1118_40_fu_4366_p1;
wire   [12:0] add_ln703_83_fu_4552_p2;
wire  signed [15:0] sext_ln708_4_fu_4369_p1;
wire  signed [14:0] sext_ln1118_41_fu_4372_p1;
wire   [14:0] add_ln703_88_fu_4583_p2;
wire  signed [11:0] sext_ln1118_44_fu_4413_p1;
wire   [11:0] add_ln703_90_fu_4598_p2;
wire  signed [15:0] sext_ln708_5_fu_4417_p1;
wire  signed [15:0] sext_ln708_6_fu_4420_p1;
wire  signed [15:0] sext_ln708_7_fu_4423_p1;
wire  signed [13:0] sext_ln708_8_fu_4463_p1;
wire   [13:0] add_ln703_99_fu_4651_p2;
wire  signed [12:0] sext_ln1118_47_fu_4467_p1;
wire   [12:0] add_ln703_100_fu_4661_p2;
wire  signed [14:0] sext_ln1118_50_fu_4508_p1;
wire   [14:0] add_ln703_106_fu_4696_p2;
wire  signed [13:0] sext_ln1118_51_fu_4512_p1;
wire   [13:0] add_ln703_107_fu_4706_p2;
wire  signed [15:0] sext_ln703_fu_4521_p1;
wire   [15:0] add_ln703_78_fu_4525_p2;
wire   [15:0] add_ln703_79_fu_4530_p2;
wire   [15:0] add_ln703_80_fu_4535_p2;
wire   [15:0] add_ln703_81_fu_4541_p2;
wire   [15:0] add_ln703_82_fu_4547_p2;
wire  signed [15:0] sext_ln703_8_fu_4558_p1;
wire   [15:0] add_ln703_84_fu_4562_p2;
wire   [15:0] add_ln703_85_fu_4568_p2;
wire   [15:0] add_ln703_86_fu_4573_p2;
wire   [15:0] add_ln703_87_fu_4578_p2;
wire  signed [15:0] sext_ln703_9_fu_4589_p1;
wire   [15:0] add_ln703_89_fu_4593_p2;
wire   [15:0] zext_ln703_fu_4604_p1;
wire   [15:0] add_ln703_91_fu_4608_p2;
wire   [15:0] add_ln703_92_fu_4613_p2;
wire   [15:0] add_ln703_93_fu_4619_p2;
wire   [15:0] add_ln703_94_fu_4625_p2;
wire   [15:0] add_ln703_95_fu_4631_p2;
wire   [15:0] add_ln703_96_fu_4636_p2;
wire   [15:0] add_ln703_97_fu_4641_p2;
wire   [15:0] add_ln703_98_fu_4646_p2;
wire  signed [15:0] sext_ln703_10_fu_4657_p1;
wire  signed [15:0] sext_ln703_11_fu_4667_p1;
wire   [15:0] add_ln703_101_fu_4671_p2;
wire   [15:0] add_ln703_102_fu_4676_p2;
wire   [15:0] add_ln703_103_fu_4681_p2;
wire   [15:0] add_ln703_104_fu_4686_p2;
wire   [15:0] add_ln703_105_fu_4691_p2;
wire  signed [15:0] sext_ln703_12_fu_4702_p1;
wire  signed [15:0] sext_ln703_13_fu_4712_p1;
wire   [15:0] add_ln703_108_fu_4716_p2;
reg    ap_ce_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;
reg   [15:0] ap_return_4_int_reg;
reg   [15:0] ap_return_5_int_reg;
reg   [15:0] ap_return_6_int_reg;
reg   [15:0] ap_return_7_int_reg;
reg   [15:0] ap_return_8_int_reg;
reg   [15:0] ap_return_9_int_reg;
reg   [15:0] ap_return_10_int_reg;
reg   [15:0] ap_return_11_int_reg;
reg   [15:0] ap_return_12_int_reg;
reg   [15:0] ap_return_13_int_reg;
reg   [15:0] ap_return_14_int_reg;
reg   [15:0] ap_return_15_int_reg;
reg   [15:0] ap_return_16_int_reg;
reg   [15:0] ap_return_17_int_reg;
reg   [15:0] ap_return_18_int_reg;
reg   [15:0] ap_return_19_int_reg;
reg   [15:0] ap_return_20_int_reg;
reg   [15:0] ap_return_21_int_reg;
reg   [15:0] ap_return_22_int_reg;
reg   [15:0] ap_return_23_int_reg;
reg   [15:0] ap_return_24_int_reg;
reg   [15:0] ap_return_25_int_reg;
reg   [15:0] ap_return_26_int_reg;
reg   [15:0] ap_return_27_int_reg;
reg   [15:0] ap_return_28_int_reg;
reg   [15:0] ap_return_29_int_reg;
reg   [15:0] ap_return_30_int_reg;
reg   [15:0] ap_return_31_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= sext_ln703_fu_4521_p1;
        ap_return_10_int_reg <= add_ln703_87_fu_4578_p2;
        ap_return_11_int_reg <= sext_ln703_9_fu_4589_p1;
        ap_return_12_int_reg <= add_ln703_89_fu_4593_p2;
        ap_return_13_int_reg[11 : 0] <= zext_ln703_fu_4604_p1[11 : 0];
        ap_return_14_int_reg <= add_ln703_91_fu_4608_p2;
        ap_return_15_int_reg <= add_ln703_92_fu_4613_p2;
        ap_return_16_int_reg <= add_ln703_93_fu_4619_p2;
        ap_return_17_int_reg <= add_ln703_94_fu_4625_p2;
        ap_return_18_int_reg <= add_ln703_95_fu_4631_p2;
        ap_return_19_int_reg <= add_ln703_96_fu_4636_p2;
        ap_return_1_int_reg <= add_ln703_78_fu_4525_p2;
        ap_return_20_int_reg <= add_ln703_97_fu_4641_p2;
        ap_return_21_int_reg <= add_ln703_98_fu_4646_p2;
        ap_return_22_int_reg <= sext_ln703_10_fu_4657_p1;
        ap_return_23_int_reg <= sext_ln703_11_fu_4667_p1;
        ap_return_24_int_reg <= add_ln703_101_fu_4671_p2;
        ap_return_25_int_reg <= add_ln703_102_fu_4676_p2;
        ap_return_26_int_reg <= add_ln703_103_fu_4681_p2;
        ap_return_27_int_reg <= add_ln703_104_fu_4686_p2;
        ap_return_28_int_reg <= add_ln703_105_fu_4691_p2;
        ap_return_29_int_reg <= sext_ln703_12_fu_4702_p1;
        ap_return_2_int_reg <= add_ln703_79_fu_4530_p2;
        ap_return_30_int_reg <= sext_ln703_13_fu_4712_p1;
        ap_return_31_int_reg <= add_ln703_108_fu_4716_p2;
        ap_return_3_int_reg <= add_ln703_80_fu_4535_p2;
        ap_return_4_int_reg <= add_ln703_81_fu_4541_p2;
        ap_return_5_int_reg <= add_ln703_82_fu_4547_p2;
        ap_return_6_int_reg <= sext_ln703_8_fu_4558_p1;
        ap_return_7_int_reg <= add_ln703_84_fu_4562_p2;
        ap_return_8_int_reg <= add_ln703_85_fu_4568_p2;
        ap_return_9_int_reg <= add_ln703_86_fu_4573_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        data_0_V_read_8_reg_4913 <= data_0_V_read;
        trunc_ln708_10_reg_4972 <= {{mul_ln1118_48_fu_209_p2[25:10]}};
        trunc_ln708_12_reg_4982 <= {{mul_ln1118_50_fu_227_p2[25:10]}};
        trunc_ln708_14_reg_4987 <= {{mul_ln1118_51_fu_210_p2[25:10]}};
        trunc_ln708_18_reg_5007 <= {{mul_ln1118_55_fu_236_p2[25:10]}};
        trunc_ln708_19_reg_5012 <= {{mul_ln1118_56_fu_222_p2[25:10]}};
        trunc_ln708_1_reg_4927 <= {{mul_ln1118_39_fu_232_p2[25:10]}};
        trunc_ln708_20_reg_5017 <= {{mul_ln1118_57_fu_230_p2[25:10]}};
        trunc_ln708_21_reg_5022 <= {{mul_ln1118_58_fu_206_p2[25:10]}};
        trunc_ln708_22_reg_4942 <= {{mul_ln1118_42_fu_229_p2[24:10]}};
        trunc_ln708_23_reg_4952 <= {{mul_ln1118_44_fu_228_p2[21:10]}};
        trunc_ln708_24_reg_5032 <= {{mul_ln1118_59_fu_235_p2[25:10]}};
        trunc_ln708_25_reg_5037 <= {{mul_ln1118_60_fu_215_p2[25:10]}};
        trunc_ln708_26_reg_5042 <= {{mul_ln1118_61_fu_233_p2[25:10]}};
        trunc_ln708_27_reg_5047 <= {{mul_ln1118_62_fu_237_p2[25:10]}};
        trunc_ln708_28_reg_5052 <= {{mul_ln1118_63_fu_216_p2[25:10]}};
        trunc_ln708_29_reg_4957 <= {{mul_ln1118_45_fu_208_p2[24:10]}};
        trunc_ln708_2_reg_4932 <= {{mul_ln1118_40_fu_211_p2[25:10]}};
        trunc_ln708_30_reg_4977 <= {{mul_ln1118_49_fu_217_p2[23:10]}};
        trunc_ln708_31_reg_5062 <= {{mul_ln1118_65_fu_231_p2[25:10]}};
        trunc_ln708_33_reg_4992 <= {{mul_ln1118_52_fu_225_p2[24:10]}};
        trunc_ln708_34_reg_4997 <= {{mul_ln1118_53_fu_234_p2[24:10]}};
        trunc_ln708_35_reg_5002 <= {{mul_ln1118_54_fu_223_p2[24:10]}};
        trunc_ln708_36_reg_5027 <= {{trunc_ln708_36_fu_4277_p1[15:4]}};
        trunc_ln708_38_reg_5057 <= {{mul_ln1118_64_fu_219_p2[22:10]}};
        trunc_ln708_5_reg_4947 <= {{mul_ln1118_43_fu_220_p2[25:10]}};
        trunc_ln708_8_reg_4962 <= {{mul_ln1118_46_fu_221_p2[25:10]}};
        trunc_ln708_9_reg_4967 <= {{mul_ln1118_47_fu_224_p2[25:10]}};
        trunc_ln708_s_reg_4937 <= {{mul_ln1118_41_fu_226_p2[24:10]}};
        trunc_ln_reg_4922 <= {{mul_ln1118_fu_214_p2[22:10]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = sext_ln703_fu_4521_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = add_ln703_78_fu_4525_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_10 = ap_return_10_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_10 = add_ln703_87_fu_4578_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_11 = ap_return_11_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_11 = sext_ln703_9_fu_4589_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_12 = ap_return_12_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_12 = add_ln703_89_fu_4593_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_13 = ap_return_13_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_13 = zext_ln703_fu_4604_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_14 = ap_return_14_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_14 = add_ln703_91_fu_4608_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_15 = ap_return_15_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_15 = add_ln703_92_fu_4613_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_16 = ap_return_16_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_16 = add_ln703_93_fu_4619_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_17 = ap_return_17_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_17 = add_ln703_94_fu_4625_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_18 = ap_return_18_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_18 = add_ln703_95_fu_4631_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_19 = ap_return_19_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_19 = add_ln703_96_fu_4636_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = add_ln703_79_fu_4530_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_20 = ap_return_20_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_20 = add_ln703_97_fu_4641_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_21 = ap_return_21_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_21 = add_ln703_98_fu_4646_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_22 = ap_return_22_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_22 = sext_ln703_10_fu_4657_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_23 = ap_return_23_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_23 = sext_ln703_11_fu_4667_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_24 = ap_return_24_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_24 = add_ln703_101_fu_4671_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_25 = ap_return_25_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_25 = add_ln703_102_fu_4676_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_26 = ap_return_26_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_26 = add_ln703_103_fu_4681_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_27 = ap_return_27_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_27 = add_ln703_104_fu_4686_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_28 = ap_return_28_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_28 = add_ln703_105_fu_4691_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_29 = ap_return_29_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_29 = sext_ln703_12_fu_4702_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = add_ln703_80_fu_4535_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_30 = ap_return_30_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_30 = sext_ln703_13_fu_4712_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_31 = ap_return_31_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_31 = add_ln703_108_fu_4716_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = add_ln703_81_fu_4541_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = add_ln703_82_fu_4547_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = sext_ln703_8_fu_4558_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_7 = ap_return_7_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_7 = add_ln703_84_fu_4562_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_8 = ap_return_8_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_8 = add_ln703_85_fu_4568_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_9 = ap_return_9_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_9 = add_ln703_86_fu_4573_p2;
    end
end

assign add_ln703_100_fu_4661_p2 = ($signed(sext_ln1118_47_fu_4467_p1) + $signed(13'd7858));

assign add_ln703_101_fu_4671_p2 = (trunc_ln708_24_reg_5032 + 16'd1048);

assign add_ln703_102_fu_4676_p2 = (trunc_ln708_25_reg_5037 + 16'd954);

assign add_ln703_103_fu_4681_p2 = (trunc_ln708_26_reg_5042 + 16'd1594);

assign add_ln703_104_fu_4686_p2 = (trunc_ln708_27_reg_5047 + 16'd211);

assign add_ln703_105_fu_4691_p2 = (trunc_ln708_28_reg_5052 + 16'd1140);

assign add_ln703_106_fu_4696_p2 = ($signed(sext_ln1118_50_fu_4508_p1) + $signed(15'd209));

assign add_ln703_107_fu_4706_p2 = ($signed(sext_ln1118_51_fu_4512_p1) + $signed(14'd307));

assign add_ln703_108_fu_4716_p2 = (trunc_ln708_31_reg_5062 + 16'd1079);

assign add_ln703_78_fu_4525_p2 = (trunc_ln708_1_reg_4927 + 16'd260);

assign add_ln703_79_fu_4530_p2 = (trunc_ln708_2_reg_4932 + 16'd567);

assign add_ln703_80_fu_4535_p2 = ($signed(sext_ln708_fu_4360_p1) + $signed(16'd351));

assign add_ln703_81_fu_4541_p2 = ($signed(sext_ln708_3_fu_4363_p1) + $signed(16'd4298));

assign add_ln703_82_fu_4547_p2 = ($signed(trunc_ln708_5_reg_4947) + $signed(16'd65430));

assign add_ln703_83_fu_4552_p2 = ($signed(sext_ln1118_40_fu_4366_p1) + $signed(13'd330));

assign add_ln703_84_fu_4562_p2 = ($signed(sext_ln708_4_fu_4369_p1) + $signed(16'd203));

assign add_ln703_85_fu_4568_p2 = (trunc_ln708_8_reg_4962 + 16'd1241);

assign add_ln703_86_fu_4573_p2 = (trunc_ln708_9_reg_4967 + 16'd1002);

assign add_ln703_87_fu_4578_p2 = (trunc_ln708_10_reg_4972 + 16'd1113);

assign add_ln703_88_fu_4583_p2 = ($signed(sext_ln1118_41_fu_4372_p1) + $signed(15'd1496));

assign add_ln703_89_fu_4593_p2 = (trunc_ln708_12_reg_4982 + 16'd2396);

assign add_ln703_90_fu_4598_p2 = ($signed(sext_ln1118_44_fu_4413_p1) + $signed(12'd1247));

assign add_ln703_91_fu_4608_p2 = (trunc_ln708_14_reg_4987 + 16'd1051);

assign add_ln703_92_fu_4613_p2 = ($signed(sext_ln708_5_fu_4417_p1) + $signed(16'd1344));

assign add_ln703_93_fu_4619_p2 = ($signed(sext_ln708_6_fu_4420_p1) + $signed(16'd65517));

assign add_ln703_94_fu_4625_p2 = ($signed(sext_ln708_7_fu_4423_p1) + $signed(16'd65535));

assign add_ln703_95_fu_4631_p2 = (trunc_ln708_18_reg_5007 + 16'd527);

assign add_ln703_96_fu_4636_p2 = ($signed(trunc_ln708_19_reg_5012) + $signed(16'd65489));

assign add_ln703_97_fu_4641_p2 = ($signed(trunc_ln708_20_reg_5017) + $signed(16'd65491));

assign add_ln703_98_fu_4646_p2 = (trunc_ln708_21_reg_5022 + 16'd28);

assign add_ln703_99_fu_4651_p2 = ($signed(sext_ln708_8_fu_4463_p1) + $signed(14'd335));

assign add_ln703_fu_4515_p2 = ($signed(sext_ln1118_fu_4357_p1) + $signed(14'd612));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign mul_ln1118_39_fu_232_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_39_fu_232_p2 = ($signed(mul_ln1118_39_fu_232_p0) * $signed('h153));

assign mul_ln1118_40_fu_211_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_40_fu_211_p2 = ($signed(mul_ln1118_40_fu_211_p0) * $signed(-'h2A5));

assign mul_ln1118_41_fu_226_p0 = sext_ln1116_cast2_fu_4029_p1;

assign mul_ln1118_41_fu_226_p2 = ($signed(mul_ln1118_41_fu_226_p0) * $signed(-'hDB));

assign mul_ln1118_42_fu_229_p0 = sext_ln1116_cast2_fu_4029_p1;

assign mul_ln1118_42_fu_229_p2 = ($signed(mul_ln1118_42_fu_229_p0) * $signed(-'hCC));

assign mul_ln1118_43_fu_220_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_43_fu_220_p2 = ($signed(mul_ln1118_43_fu_220_p0) * $signed('h14A));

assign mul_ln1118_44_fu_228_p0 = sext_ln1116_cast3_fu_4024_p0;

assign mul_ln1118_44_fu_228_p2 = ($signed(mul_ln1118_44_fu_228_p0) * $signed('h16));

assign mul_ln1118_45_fu_208_p0 = sext_ln1116_cast2_fu_4029_p1;

assign mul_ln1118_45_fu_208_p2 = ($signed(mul_ln1118_45_fu_208_p0) * $signed(-'hDF));

assign mul_ln1118_46_fu_221_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_46_fu_221_p2 = ($signed(mul_ln1118_46_fu_221_p0) * $signed('h215));

assign mul_ln1118_47_fu_224_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_47_fu_224_p2 = ($signed(mul_ln1118_47_fu_224_p0) * $signed('h15A));

assign mul_ln1118_48_fu_209_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_48_fu_209_p2 = ($signed(mul_ln1118_48_fu_209_p0) * $signed('h1B1));

assign mul_ln1118_49_fu_217_p0 = sext_ln1116_cast4_fu_4019_p0;

assign mul_ln1118_49_fu_217_p2 = ($signed(mul_ln1118_49_fu_217_p0) * $signed('h73));

assign mul_ln1118_50_fu_227_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_50_fu_227_p2 = ($signed(mul_ln1118_50_fu_227_p0) * $signed('h731));

assign mul_ln1118_51_fu_210_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_51_fu_210_p2 = ($signed(mul_ln1118_51_fu_210_p0) * $signed(-'h394));

assign mul_ln1118_52_fu_225_p0 = sext_ln1116_cast2_fu_4029_p1;

assign mul_ln1118_52_fu_225_p2 = ($signed(mul_ln1118_52_fu_225_p0) * $signed(-'hFD));

assign mul_ln1118_53_fu_234_p0 = sext_ln1116_cast2_fu_4029_p1;

assign mul_ln1118_53_fu_234_p2 = ($signed(mul_ln1118_53_fu_234_p0) * $signed('h98));

assign mul_ln1118_54_fu_223_p0 = sext_ln1116_cast2_fu_4029_p1;

assign mul_ln1118_54_fu_223_p2 = ($signed(mul_ln1118_54_fu_223_p0) * $signed(-'h87));

assign mul_ln1118_55_fu_236_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_55_fu_236_p2 = ($signed(mul_ln1118_55_fu_236_p0) * $signed('h16A));

assign mul_ln1118_56_fu_222_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_56_fu_222_p2 = ($signed(mul_ln1118_56_fu_222_p0) * $signed(-'h138));

assign mul_ln1118_57_fu_230_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_57_fu_230_p2 = ($signed(mul_ln1118_57_fu_230_p0) * $signed('h1A1));

assign mul_ln1118_58_fu_206_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_58_fu_206_p2 = ($signed(mul_ln1118_58_fu_206_p0) * $signed(-'h158));

assign mul_ln1118_59_fu_235_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_59_fu_235_p2 = ($signed(mul_ln1118_59_fu_235_p0) * $signed('h2BB));

assign mul_ln1118_60_fu_215_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_60_fu_215_p2 = ($signed(mul_ln1118_60_fu_215_p0) * $signed('h614));

assign mul_ln1118_61_fu_233_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_61_fu_233_p2 = ($signed(mul_ln1118_61_fu_233_p0) * $signed('h867));

assign mul_ln1118_62_fu_237_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_62_fu_237_p2 = ($signed(mul_ln1118_62_fu_237_p0) * $signed(-'h3FA));

assign mul_ln1118_63_fu_216_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_63_fu_216_p2 = ($signed(mul_ln1118_63_fu_216_p0) * $signed('h3D3));

assign mul_ln1118_64_fu_219_p0 = sext_ln1116_cast_fu_4061_p1;

assign mul_ln1118_64_fu_219_p2 = ($signed(mul_ln1118_64_fu_219_p0) * $signed(-'h2B));

assign mul_ln1118_65_fu_231_p0 = sext_ln1116_cast1_fu_4039_p1;

assign mul_ln1118_65_fu_231_p2 = ($signed(mul_ln1118_65_fu_231_p0) * $signed('h47C));

assign mul_ln1118_fu_214_p0 = sext_ln1116_cast_fu_4061_p1;

assign mul_ln1118_fu_214_p2 = ($signed(mul_ln1118_fu_214_p0) * $signed(-'h36));

assign sext_ln1116_cast1_fu_4039_p0 = data_0_V_read;

assign sext_ln1116_cast1_fu_4039_p1 = sext_ln1116_cast1_fu_4039_p0;

assign sext_ln1116_cast2_fu_4029_p0 = data_0_V_read;

assign sext_ln1116_cast2_fu_4029_p1 = sext_ln1116_cast2_fu_4029_p0;

assign sext_ln1116_cast3_fu_4024_p0 = data_0_V_read;

assign sext_ln1116_cast4_fu_4019_p0 = data_0_V_read;

assign sext_ln1116_cast_fu_4061_p0 = data_0_V_read;

assign sext_ln1116_cast_fu_4061_p1 = sext_ln1116_cast_fu_4061_p0;

assign sext_ln1118_40_fu_4366_p1 = $signed(trunc_ln708_23_reg_4952);

assign sext_ln1118_41_fu_4372_p1 = $signed(trunc_ln708_30_reg_4977);

assign sext_ln1118_42_fu_4382_p1 = shl_ln_fu_4375_p3;

assign sext_ln1118_43_fu_4393_p1 = $signed(shl_ln1118_s_fu_4386_p3);

assign sext_ln1118_44_fu_4413_p1 = $signed(trunc_ln708_32_fu_4403_p4);

assign sext_ln1118_45_fu_4433_p1 = $signed(shl_ln1118_70_fu_4426_p3);

assign sext_ln1118_46_fu_4443_p1 = shl_ln_fu_4375_p3;

assign sext_ln1118_47_fu_4467_p1 = $signed(trunc_ln708_36_reg_5027);

assign sext_ln1118_48_fu_4477_p1 = $signed(shl_ln1118_71_fu_4470_p3);

assign sext_ln1118_49_fu_4488_p1 = $signed(shl_ln1118_72_fu_4481_p3);

assign sext_ln1118_50_fu_4508_p1 = $signed(trunc_ln708_37_fu_4498_p4);

assign sext_ln1118_51_fu_4512_p1 = $signed(trunc_ln708_38_reg_5057);

assign sext_ln1118_fu_4357_p1 = $signed(trunc_ln_reg_4922);

assign sext_ln703_10_fu_4657_p1 = $signed(add_ln703_99_fu_4651_p2);

assign sext_ln703_11_fu_4667_p1 = $signed(add_ln703_100_fu_4661_p2);

assign sext_ln703_12_fu_4702_p1 = $signed(add_ln703_106_fu_4696_p2);

assign sext_ln703_13_fu_4712_p1 = $signed(add_ln703_107_fu_4706_p2);

assign sext_ln703_8_fu_4558_p1 = $signed(add_ln703_83_fu_4552_p2);

assign sext_ln703_9_fu_4589_p1 = $signed(add_ln703_88_fu_4583_p2);

assign sext_ln703_fu_4521_p1 = $signed(add_ln703_fu_4515_p2);

assign sext_ln708_3_fu_4363_p1 = $signed(trunc_ln708_22_reg_4942);

assign sext_ln708_4_fu_4369_p1 = $signed(trunc_ln708_29_reg_4957);

assign sext_ln708_5_fu_4417_p1 = $signed(trunc_ln708_33_reg_4992);

assign sext_ln708_6_fu_4420_p1 = $signed(trunc_ln708_34_reg_4997);

assign sext_ln708_7_fu_4423_p1 = $signed(trunc_ln708_35_reg_5002);

assign sext_ln708_8_fu_4463_p1 = $signed(tmp_fu_4453_p4);

assign sext_ln708_fu_4360_p1 = $signed(trunc_ln708_s_reg_4937);

assign shl_ln1118_70_fu_4426_p3 = {{data_0_V_read_8_reg_4913}, {6'd0}};

assign shl_ln1118_71_fu_4470_p3 = {{data_0_V_read_8_reg_4913}, {7'd0}};

assign shl_ln1118_72_fu_4481_p3 = {{data_0_V_read_8_reg_4913}, {3'd0}};

assign shl_ln1118_s_fu_4386_p3 = {{data_0_V_read_8_reg_4913}, {1'd0}};

assign shl_ln_fu_4375_p3 = {{data_0_V_read_8_reg_4913}, {4'd0}};

assign sub_ln1118_1_fu_4437_p2 = ($signed(23'd0) - $signed(sext_ln1118_45_fu_4433_p1));

assign sub_ln1118_2_fu_4447_p2 = ($signed(sub_ln1118_1_fu_4437_p2) - $signed(sext_ln1118_46_fu_4443_p1));

assign sub_ln1118_3_fu_4492_p2 = ($signed(sext_ln1118_48_fu_4477_p1) - $signed(sext_ln1118_49_fu_4488_p1));

assign sub_ln1118_fu_4397_p2 = ($signed(sext_ln1118_43_fu_4393_p1) - $signed(sext_ln1118_42_fu_4382_p1));

assign tmp_fu_4453_p4 = {{sub_ln1118_2_fu_4447_p2[22:10]}};

assign trunc_ln708_32_fu_4403_p4 = {{sub_ln1118_fu_4397_p2[20:10]}};

assign trunc_ln708_36_fu_4277_p1 = data_0_V_read;

assign trunc_ln708_37_fu_4498_p4 = {{sub_ln1118_3_fu_4492_p2[23:10]}};

assign zext_ln703_fu_4604_p1 = add_ln703_90_fu_4598_p2;

always @ (posedge ap_clk) begin
    ap_return_13_int_reg[15:12] <= 4'b0000;
end

endmodule //dense_simple_0_0_1
