// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module tanh (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_V_read,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] data_V_read;
output  [10:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [9:0] tanh_table9_address0;
reg    tanh_table9_ce0;
wire   [10:0] tanh_table9_q0;
wire   [9:0] trunc_ln322_fu_181_p1;
reg   [9:0] trunc_ln322_reg_212;
wire   [0:0] icmp_ln323_fu_195_p2;
reg   [0:0] icmp_ln323_reg_217;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln324_fu_207_p1;
wire   [12:0] tmp_1_fu_89_p4;
wire   [25:0] r_V_fu_81_p3;
wire   [2:0] trunc_ln851_fu_109_p1;
wire   [9:0] p_Result_2_fu_113_p3;
wire  signed [13:0] sext_ln835_fu_99_p1;
wire   [0:0] icmp_ln851_fu_121_p2;
wire   [13:0] ret_V_fu_127_p2;
wire   [0:0] p_Result_s_fu_103_p2;
wire   [13:0] select_ln851_fu_133_p3;
wire   [13:0] select_ln850_fu_141_p3;
wire   [12:0] trunc_ln320_fu_149_p1;
wire   [13:0] index_fu_153_p2;
wire   [0:0] tmp_2_fu_165_p3;
wire   [12:0] add_ln320_1_fu_159_p2;
wire   [12:0] select_ln322_fu_173_p3;
wire   [2:0] tmp_3_fu_185_p4;
wire   [9:0] select_ln323_fu_201_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

tanh_tanh_table9 #(
    .DataWidth( 11 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
tanh_table9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tanh_table9_address0),
    .ce0(tanh_table9_ce0),
    .q0(tanh_table9_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln323_reg_217 <= icmp_ln323_fu_195_p2;
        trunc_ln322_reg_212 <= trunc_ln322_fu_181_p1;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table9_ce0 = 1'b1;
    end else begin
        tanh_table9_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln320_1_fu_159_p2 = (13'd512 + trunc_ln320_fu_149_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = tanh_table9_q0;

assign icmp_ln323_fu_195_p2 = ((tmp_3_fu_185_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_fu_121_p2 = ((p_Result_2_fu_113_p3 == 10'd0) ? 1'b1 : 1'b0);

assign index_fu_153_p2 = (14'd512 + select_ln850_fu_141_p3);

assign p_Result_2_fu_113_p3 = {{trunc_ln851_fu_109_p1}, {7'd0}};

assign p_Result_s_fu_103_p2 = (($signed(r_V_fu_81_p3) < $signed(26'd67108857)) ? 1'b1 : 1'b0);

assign r_V_fu_81_p3 = {{data_V_read}, {10'd0}};

assign ret_V_fu_127_p2 = ($signed(14'd1) + $signed(sext_ln835_fu_99_p1));

assign select_ln322_fu_173_p3 = ((tmp_2_fu_165_p3[0:0] === 1'b1) ? 13'd0 : add_ln320_1_fu_159_p2);

assign select_ln323_fu_201_p3 = ((icmp_ln323_reg_217[0:0] === 1'b1) ? 10'd1023 : trunc_ln322_reg_212);

assign select_ln850_fu_141_p3 = ((p_Result_s_fu_103_p2[0:0] === 1'b1) ? select_ln851_fu_133_p3 : sext_ln835_fu_99_p1);

assign select_ln851_fu_133_p3 = ((icmp_ln851_fu_121_p2[0:0] === 1'b1) ? sext_ln835_fu_99_p1 : ret_V_fu_127_p2);

assign sext_ln835_fu_99_p1 = $signed(tmp_1_fu_89_p4);

assign tanh_table9_address0 = zext_ln324_fu_207_p1;

assign tmp_1_fu_89_p4 = {{data_V_read[15:3]}};

assign tmp_2_fu_165_p3 = index_fu_153_p2[32'd13];

assign tmp_3_fu_185_p4 = {{select_ln322_fu_173_p3[12:10]}};

assign trunc_ln320_fu_149_p1 = select_ln850_fu_141_p3[12:0];

assign trunc_ln322_fu_181_p1 = select_ln322_fu_173_p3[9:0];

assign trunc_ln851_fu_109_p1 = data_V_read[2:0];

assign zext_ln324_fu_207_p1 = select_ln323_fu_201_p3;

endmodule //tanh
