// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "hard_tanh.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic hard_tanh::ap_const_logic_1 = sc_dt::Log_1;
const bool hard_tanh::ap_const_boolean_1 = true;
const sc_lv<16> hard_tanh::ap_const_lv16_400 = "10000000000";
const sc_lv<16> hard_tanh::ap_const_lv16_FC00 = "1111110000000000";
const sc_lv<12> hard_tanh::ap_const_lv12_400 = "10000000000";
const sc_lv<12> hard_tanh::ap_const_lv12_C00 = "110000000000";
const sc_logic hard_tanh::ap_const_logic_0 = sc_dt::Log_0;

hard_tanh::hard_tanh(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( sext_ln1494_fu_322_p1 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( sext_ln1494_1_fu_364_p1 );

    SC_METHOD(thread_ap_return_10);
    sensitive << ( sext_ln1494_10_fu_742_p1 );

    SC_METHOD(thread_ap_return_11);
    sensitive << ( sext_ln1494_11_fu_784_p1 );

    SC_METHOD(thread_ap_return_12);
    sensitive << ( sext_ln1494_12_fu_826_p1 );

    SC_METHOD(thread_ap_return_13);
    sensitive << ( sext_ln1494_13_fu_868_p1 );

    SC_METHOD(thread_ap_return_14);
    sensitive << ( sext_ln1494_14_fu_910_p1 );

    SC_METHOD(thread_ap_return_15);
    sensitive << ( sext_ln1494_15_fu_952_p1 );

    SC_METHOD(thread_ap_return_16);
    sensitive << ( sext_ln1494_16_fu_994_p1 );

    SC_METHOD(thread_ap_return_17);
    sensitive << ( sext_ln1494_17_fu_1036_p1 );

    SC_METHOD(thread_ap_return_18);
    sensitive << ( sext_ln1494_18_fu_1078_p1 );

    SC_METHOD(thread_ap_return_19);
    sensitive << ( sext_ln1494_19_fu_1120_p1 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( sext_ln1494_2_fu_406_p1 );

    SC_METHOD(thread_ap_return_20);
    sensitive << ( sext_ln1494_20_fu_1162_p1 );

    SC_METHOD(thread_ap_return_21);
    sensitive << ( sext_ln1494_21_fu_1204_p1 );

    SC_METHOD(thread_ap_return_22);
    sensitive << ( sext_ln1494_22_fu_1246_p1 );

    SC_METHOD(thread_ap_return_23);
    sensitive << ( sext_ln1494_23_fu_1288_p1 );

    SC_METHOD(thread_ap_return_24);
    sensitive << ( sext_ln1494_24_fu_1330_p1 );

    SC_METHOD(thread_ap_return_25);
    sensitive << ( sext_ln1494_25_fu_1372_p1 );

    SC_METHOD(thread_ap_return_26);
    sensitive << ( sext_ln1494_26_fu_1414_p1 );

    SC_METHOD(thread_ap_return_27);
    sensitive << ( sext_ln1494_27_fu_1456_p1 );

    SC_METHOD(thread_ap_return_28);
    sensitive << ( sext_ln1494_28_fu_1498_p1 );

    SC_METHOD(thread_ap_return_29);
    sensitive << ( sext_ln1494_29_fu_1540_p1 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( sext_ln1494_3_fu_448_p1 );

    SC_METHOD(thread_ap_return_30);
    sensitive << ( sext_ln1494_30_fu_1582_p1 );

    SC_METHOD(thread_ap_return_31);
    sensitive << ( sext_ln331_fu_1624_p1 );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( sext_ln1494_4_fu_490_p1 );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( sext_ln1494_5_fu_532_p1 );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( sext_ln1494_6_fu_574_p1 );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( sext_ln1494_7_fu_616_p1 );

    SC_METHOD(thread_ap_return_8);
    sensitive << ( sext_ln1494_8_fu_658_p1 );

    SC_METHOD(thread_ap_return_9);
    sensitive << ( sext_ln1494_9_fu_700_p1 );

    SC_METHOD(thread_icmp_ln1494_10_fu_704_p2);
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_icmp_ln1494_11_fu_746_p2);
    sensitive << ( data_11_V_read );

    SC_METHOD(thread_icmp_ln1494_12_fu_788_p2);
    sensitive << ( data_12_V_read );

    SC_METHOD(thread_icmp_ln1494_13_fu_830_p2);
    sensitive << ( data_13_V_read );

    SC_METHOD(thread_icmp_ln1494_14_fu_872_p2);
    sensitive << ( data_14_V_read );

    SC_METHOD(thread_icmp_ln1494_15_fu_914_p2);
    sensitive << ( data_15_V_read );

    SC_METHOD(thread_icmp_ln1494_16_fu_956_p2);
    sensitive << ( data_16_V_read );

    SC_METHOD(thread_icmp_ln1494_17_fu_998_p2);
    sensitive << ( data_17_V_read );

    SC_METHOD(thread_icmp_ln1494_18_fu_1040_p2);
    sensitive << ( data_18_V_read );

    SC_METHOD(thread_icmp_ln1494_19_fu_1082_p2);
    sensitive << ( data_19_V_read );

    SC_METHOD(thread_icmp_ln1494_1_fu_326_p2);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_icmp_ln1494_20_fu_1124_p2);
    sensitive << ( data_20_V_read );

    SC_METHOD(thread_icmp_ln1494_21_fu_1166_p2);
    sensitive << ( data_21_V_read );

    SC_METHOD(thread_icmp_ln1494_22_fu_1208_p2);
    sensitive << ( data_22_V_read );

    SC_METHOD(thread_icmp_ln1494_23_fu_1250_p2);
    sensitive << ( data_23_V_read );

    SC_METHOD(thread_icmp_ln1494_24_fu_1292_p2);
    sensitive << ( data_24_V_read );

    SC_METHOD(thread_icmp_ln1494_25_fu_1334_p2);
    sensitive << ( data_25_V_read );

    SC_METHOD(thread_icmp_ln1494_26_fu_1376_p2);
    sensitive << ( data_26_V_read );

    SC_METHOD(thread_icmp_ln1494_27_fu_1418_p2);
    sensitive << ( data_27_V_read );

    SC_METHOD(thread_icmp_ln1494_28_fu_1460_p2);
    sensitive << ( data_28_V_read );

    SC_METHOD(thread_icmp_ln1494_29_fu_1502_p2);
    sensitive << ( data_29_V_read );

    SC_METHOD(thread_icmp_ln1494_2_fu_368_p2);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_icmp_ln1494_30_fu_1544_p2);
    sensitive << ( data_30_V_read );

    SC_METHOD(thread_icmp_ln1494_31_fu_1586_p2);
    sensitive << ( data_31_V_read );

    SC_METHOD(thread_icmp_ln1494_3_fu_410_p2);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_icmp_ln1494_4_fu_452_p2);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_icmp_ln1494_5_fu_494_p2);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_icmp_ln1494_6_fu_536_p2);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_icmp_ln1494_7_fu_578_p2);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_icmp_ln1494_8_fu_620_p2);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_icmp_ln1494_9_fu_662_p2);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_icmp_ln1494_fu_284_p2);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_icmp_ln1495_10_fu_710_p2);
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_icmp_ln1495_11_fu_752_p2);
    sensitive << ( data_11_V_read );

    SC_METHOD(thread_icmp_ln1495_12_fu_794_p2);
    sensitive << ( data_12_V_read );

    SC_METHOD(thread_icmp_ln1495_13_fu_836_p2);
    sensitive << ( data_13_V_read );

    SC_METHOD(thread_icmp_ln1495_14_fu_878_p2);
    sensitive << ( data_14_V_read );

    SC_METHOD(thread_icmp_ln1495_15_fu_920_p2);
    sensitive << ( data_15_V_read );

    SC_METHOD(thread_icmp_ln1495_16_fu_962_p2);
    sensitive << ( data_16_V_read );

    SC_METHOD(thread_icmp_ln1495_17_fu_1004_p2);
    sensitive << ( data_17_V_read );

    SC_METHOD(thread_icmp_ln1495_18_fu_1046_p2);
    sensitive << ( data_18_V_read );

    SC_METHOD(thread_icmp_ln1495_19_fu_1088_p2);
    sensitive << ( data_19_V_read );

    SC_METHOD(thread_icmp_ln1495_1_fu_332_p2);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_icmp_ln1495_20_fu_1130_p2);
    sensitive << ( data_20_V_read );

    SC_METHOD(thread_icmp_ln1495_21_fu_1172_p2);
    sensitive << ( data_21_V_read );

    SC_METHOD(thread_icmp_ln1495_22_fu_1214_p2);
    sensitive << ( data_22_V_read );

    SC_METHOD(thread_icmp_ln1495_23_fu_1256_p2);
    sensitive << ( data_23_V_read );

    SC_METHOD(thread_icmp_ln1495_24_fu_1298_p2);
    sensitive << ( data_24_V_read );

    SC_METHOD(thread_icmp_ln1495_25_fu_1340_p2);
    sensitive << ( data_25_V_read );

    SC_METHOD(thread_icmp_ln1495_26_fu_1382_p2);
    sensitive << ( data_26_V_read );

    SC_METHOD(thread_icmp_ln1495_27_fu_1424_p2);
    sensitive << ( data_27_V_read );

    SC_METHOD(thread_icmp_ln1495_28_fu_1466_p2);
    sensitive << ( data_28_V_read );

    SC_METHOD(thread_icmp_ln1495_29_fu_1508_p2);
    sensitive << ( data_29_V_read );

    SC_METHOD(thread_icmp_ln1495_2_fu_374_p2);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_icmp_ln1495_30_fu_1550_p2);
    sensitive << ( data_30_V_read );

    SC_METHOD(thread_icmp_ln1495_31_fu_1592_p2);
    sensitive << ( data_31_V_read );

    SC_METHOD(thread_icmp_ln1495_3_fu_416_p2);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_icmp_ln1495_4_fu_458_p2);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_icmp_ln1495_5_fu_500_p2);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_icmp_ln1495_6_fu_542_p2);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_icmp_ln1495_7_fu_584_p2);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_icmp_ln1495_8_fu_626_p2);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_icmp_ln1495_9_fu_668_p2);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_icmp_ln1495_fu_290_p2);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_or_ln1494_10_fu_728_p2);
    sensitive << ( icmp_ln1494_10_fu_704_p2 );
    sensitive << ( icmp_ln1495_10_fu_710_p2 );

    SC_METHOD(thread_or_ln1494_11_fu_770_p2);
    sensitive << ( icmp_ln1494_11_fu_746_p2 );
    sensitive << ( icmp_ln1495_11_fu_752_p2 );

    SC_METHOD(thread_or_ln1494_12_fu_812_p2);
    sensitive << ( icmp_ln1494_12_fu_788_p2 );
    sensitive << ( icmp_ln1495_12_fu_794_p2 );

    SC_METHOD(thread_or_ln1494_13_fu_854_p2);
    sensitive << ( icmp_ln1494_13_fu_830_p2 );
    sensitive << ( icmp_ln1495_13_fu_836_p2 );

    SC_METHOD(thread_or_ln1494_14_fu_896_p2);
    sensitive << ( icmp_ln1494_14_fu_872_p2 );
    sensitive << ( icmp_ln1495_14_fu_878_p2 );

    SC_METHOD(thread_or_ln1494_15_fu_938_p2);
    sensitive << ( icmp_ln1494_15_fu_914_p2 );
    sensitive << ( icmp_ln1495_15_fu_920_p2 );

    SC_METHOD(thread_or_ln1494_16_fu_980_p2);
    sensitive << ( icmp_ln1494_16_fu_956_p2 );
    sensitive << ( icmp_ln1495_16_fu_962_p2 );

    SC_METHOD(thread_or_ln1494_17_fu_1022_p2);
    sensitive << ( icmp_ln1494_17_fu_998_p2 );
    sensitive << ( icmp_ln1495_17_fu_1004_p2 );

    SC_METHOD(thread_or_ln1494_18_fu_1064_p2);
    sensitive << ( icmp_ln1494_18_fu_1040_p2 );
    sensitive << ( icmp_ln1495_18_fu_1046_p2 );

    SC_METHOD(thread_or_ln1494_19_fu_1106_p2);
    sensitive << ( icmp_ln1494_19_fu_1082_p2 );
    sensitive << ( icmp_ln1495_19_fu_1088_p2 );

    SC_METHOD(thread_or_ln1494_1_fu_350_p2);
    sensitive << ( icmp_ln1494_1_fu_326_p2 );
    sensitive << ( icmp_ln1495_1_fu_332_p2 );

    SC_METHOD(thread_or_ln1494_20_fu_1148_p2);
    sensitive << ( icmp_ln1494_20_fu_1124_p2 );
    sensitive << ( icmp_ln1495_20_fu_1130_p2 );

    SC_METHOD(thread_or_ln1494_21_fu_1190_p2);
    sensitive << ( icmp_ln1494_21_fu_1166_p2 );
    sensitive << ( icmp_ln1495_21_fu_1172_p2 );

    SC_METHOD(thread_or_ln1494_22_fu_1232_p2);
    sensitive << ( icmp_ln1494_22_fu_1208_p2 );
    sensitive << ( icmp_ln1495_22_fu_1214_p2 );

    SC_METHOD(thread_or_ln1494_23_fu_1274_p2);
    sensitive << ( icmp_ln1494_23_fu_1250_p2 );
    sensitive << ( icmp_ln1495_23_fu_1256_p2 );

    SC_METHOD(thread_or_ln1494_24_fu_1316_p2);
    sensitive << ( icmp_ln1494_24_fu_1292_p2 );
    sensitive << ( icmp_ln1495_24_fu_1298_p2 );

    SC_METHOD(thread_or_ln1494_25_fu_1358_p2);
    sensitive << ( icmp_ln1494_25_fu_1334_p2 );
    sensitive << ( icmp_ln1495_25_fu_1340_p2 );

    SC_METHOD(thread_or_ln1494_26_fu_1400_p2);
    sensitive << ( icmp_ln1494_26_fu_1376_p2 );
    sensitive << ( icmp_ln1495_26_fu_1382_p2 );

    SC_METHOD(thread_or_ln1494_27_fu_1442_p2);
    sensitive << ( icmp_ln1494_27_fu_1418_p2 );
    sensitive << ( icmp_ln1495_27_fu_1424_p2 );

    SC_METHOD(thread_or_ln1494_28_fu_1484_p2);
    sensitive << ( icmp_ln1494_28_fu_1460_p2 );
    sensitive << ( icmp_ln1495_28_fu_1466_p2 );

    SC_METHOD(thread_or_ln1494_29_fu_1526_p2);
    sensitive << ( icmp_ln1494_29_fu_1502_p2 );
    sensitive << ( icmp_ln1495_29_fu_1508_p2 );

    SC_METHOD(thread_or_ln1494_2_fu_392_p2);
    sensitive << ( icmp_ln1494_2_fu_368_p2 );
    sensitive << ( icmp_ln1495_2_fu_374_p2 );

    SC_METHOD(thread_or_ln1494_30_fu_1568_p2);
    sensitive << ( icmp_ln1494_30_fu_1544_p2 );
    sensitive << ( icmp_ln1495_30_fu_1550_p2 );

    SC_METHOD(thread_or_ln1494_31_fu_1610_p2);
    sensitive << ( icmp_ln1494_31_fu_1586_p2 );
    sensitive << ( icmp_ln1495_31_fu_1592_p2 );

    SC_METHOD(thread_or_ln1494_3_fu_434_p2);
    sensitive << ( icmp_ln1494_3_fu_410_p2 );
    sensitive << ( icmp_ln1495_3_fu_416_p2 );

    SC_METHOD(thread_or_ln1494_4_fu_476_p2);
    sensitive << ( icmp_ln1494_4_fu_452_p2 );
    sensitive << ( icmp_ln1495_4_fu_458_p2 );

    SC_METHOD(thread_or_ln1494_5_fu_518_p2);
    sensitive << ( icmp_ln1494_5_fu_494_p2 );
    sensitive << ( icmp_ln1495_5_fu_500_p2 );

    SC_METHOD(thread_or_ln1494_6_fu_560_p2);
    sensitive << ( icmp_ln1494_6_fu_536_p2 );
    sensitive << ( icmp_ln1495_6_fu_542_p2 );

    SC_METHOD(thread_or_ln1494_7_fu_602_p2);
    sensitive << ( icmp_ln1494_7_fu_578_p2 );
    sensitive << ( icmp_ln1495_7_fu_584_p2 );

    SC_METHOD(thread_or_ln1494_8_fu_644_p2);
    sensitive << ( icmp_ln1494_8_fu_620_p2 );
    sensitive << ( icmp_ln1495_8_fu_626_p2 );

    SC_METHOD(thread_or_ln1494_9_fu_686_p2);
    sensitive << ( icmp_ln1494_9_fu_662_p2 );
    sensitive << ( icmp_ln1495_9_fu_668_p2 );

    SC_METHOD(thread_or_ln1494_fu_308_p2);
    sensitive << ( icmp_ln1494_fu_284_p2 );
    sensitive << ( icmp_ln1495_fu_290_p2 );

    SC_METHOD(thread_select_ln1494_10_fu_510_p3);
    sensitive << ( icmp_ln1494_5_fu_494_p2 );

    SC_METHOD(thread_select_ln1494_12_fu_552_p3);
    sensitive << ( icmp_ln1494_6_fu_536_p2 );

    SC_METHOD(thread_select_ln1494_14_fu_594_p3);
    sensitive << ( icmp_ln1494_7_fu_578_p2 );

    SC_METHOD(thread_select_ln1494_16_fu_636_p3);
    sensitive << ( icmp_ln1494_8_fu_620_p2 );

    SC_METHOD(thread_select_ln1494_18_fu_678_p3);
    sensitive << ( icmp_ln1494_9_fu_662_p2 );

    SC_METHOD(thread_select_ln1494_20_fu_720_p3);
    sensitive << ( icmp_ln1494_10_fu_704_p2 );

    SC_METHOD(thread_select_ln1494_22_fu_762_p3);
    sensitive << ( icmp_ln1494_11_fu_746_p2 );

    SC_METHOD(thread_select_ln1494_24_fu_804_p3);
    sensitive << ( icmp_ln1494_12_fu_788_p2 );

    SC_METHOD(thread_select_ln1494_26_fu_846_p3);
    sensitive << ( icmp_ln1494_13_fu_830_p2 );

    SC_METHOD(thread_select_ln1494_28_fu_888_p3);
    sensitive << ( icmp_ln1494_14_fu_872_p2 );

    SC_METHOD(thread_select_ln1494_2_fu_342_p3);
    sensitive << ( icmp_ln1494_1_fu_326_p2 );

    SC_METHOD(thread_select_ln1494_30_fu_930_p3);
    sensitive << ( icmp_ln1494_15_fu_914_p2 );

    SC_METHOD(thread_select_ln1494_32_fu_972_p3);
    sensitive << ( icmp_ln1494_16_fu_956_p2 );

    SC_METHOD(thread_select_ln1494_34_fu_1014_p3);
    sensitive << ( icmp_ln1494_17_fu_998_p2 );

    SC_METHOD(thread_select_ln1494_36_fu_1056_p3);
    sensitive << ( icmp_ln1494_18_fu_1040_p2 );

    SC_METHOD(thread_select_ln1494_38_fu_1098_p3);
    sensitive << ( icmp_ln1494_19_fu_1082_p2 );

    SC_METHOD(thread_select_ln1494_40_fu_1140_p3);
    sensitive << ( icmp_ln1494_20_fu_1124_p2 );

    SC_METHOD(thread_select_ln1494_42_fu_1182_p3);
    sensitive << ( icmp_ln1494_21_fu_1166_p2 );

    SC_METHOD(thread_select_ln1494_44_fu_1224_p3);
    sensitive << ( icmp_ln1494_22_fu_1208_p2 );

    SC_METHOD(thread_select_ln1494_46_fu_1266_p3);
    sensitive << ( icmp_ln1494_23_fu_1250_p2 );

    SC_METHOD(thread_select_ln1494_48_fu_1308_p3);
    sensitive << ( icmp_ln1494_24_fu_1292_p2 );

    SC_METHOD(thread_select_ln1494_4_fu_384_p3);
    sensitive << ( icmp_ln1494_2_fu_368_p2 );

    SC_METHOD(thread_select_ln1494_50_fu_1350_p3);
    sensitive << ( icmp_ln1494_25_fu_1334_p2 );

    SC_METHOD(thread_select_ln1494_52_fu_1392_p3);
    sensitive << ( icmp_ln1494_26_fu_1376_p2 );

    SC_METHOD(thread_select_ln1494_54_fu_1434_p3);
    sensitive << ( icmp_ln1494_27_fu_1418_p2 );

    SC_METHOD(thread_select_ln1494_56_fu_1476_p3);
    sensitive << ( icmp_ln1494_28_fu_1460_p2 );

    SC_METHOD(thread_select_ln1494_58_fu_1518_p3);
    sensitive << ( icmp_ln1494_29_fu_1502_p2 );

    SC_METHOD(thread_select_ln1494_60_fu_1560_p3);
    sensitive << ( icmp_ln1494_30_fu_1544_p2 );

    SC_METHOD(thread_select_ln1494_62_fu_1602_p3);
    sensitive << ( icmp_ln1494_31_fu_1586_p2 );

    SC_METHOD(thread_select_ln1494_64_fu_314_p3);
    sensitive << ( or_ln1494_fu_308_p2 );
    sensitive << ( select_ln1494_fu_300_p3 );
    sensitive << ( trunc_ln347_fu_296_p1 );

    SC_METHOD(thread_select_ln1494_65_fu_356_p3);
    sensitive << ( or_ln1494_1_fu_350_p2 );
    sensitive << ( select_ln1494_2_fu_342_p3 );
    sensitive << ( trunc_ln347_32_fu_338_p1 );

    SC_METHOD(thread_select_ln1494_66_fu_398_p3);
    sensitive << ( or_ln1494_2_fu_392_p2 );
    sensitive << ( select_ln1494_4_fu_384_p3 );
    sensitive << ( trunc_ln347_33_fu_380_p1 );

    SC_METHOD(thread_select_ln1494_67_fu_440_p3);
    sensitive << ( or_ln1494_3_fu_434_p2 );
    sensitive << ( select_ln1494_6_fu_426_p3 );
    sensitive << ( trunc_ln347_34_fu_422_p1 );

    SC_METHOD(thread_select_ln1494_68_fu_482_p3);
    sensitive << ( or_ln1494_4_fu_476_p2 );
    sensitive << ( select_ln1494_8_fu_468_p3 );
    sensitive << ( trunc_ln347_35_fu_464_p1 );

    SC_METHOD(thread_select_ln1494_69_fu_524_p3);
    sensitive << ( or_ln1494_5_fu_518_p2 );
    sensitive << ( select_ln1494_10_fu_510_p3 );
    sensitive << ( trunc_ln347_36_fu_506_p1 );

    SC_METHOD(thread_select_ln1494_6_fu_426_p3);
    sensitive << ( icmp_ln1494_3_fu_410_p2 );

    SC_METHOD(thread_select_ln1494_70_fu_566_p3);
    sensitive << ( or_ln1494_6_fu_560_p2 );
    sensitive << ( select_ln1494_12_fu_552_p3 );
    sensitive << ( trunc_ln347_37_fu_548_p1 );

    SC_METHOD(thread_select_ln1494_71_fu_608_p3);
    sensitive << ( or_ln1494_7_fu_602_p2 );
    sensitive << ( select_ln1494_14_fu_594_p3 );
    sensitive << ( trunc_ln347_38_fu_590_p1 );

    SC_METHOD(thread_select_ln1494_72_fu_650_p3);
    sensitive << ( or_ln1494_8_fu_644_p2 );
    sensitive << ( select_ln1494_16_fu_636_p3 );
    sensitive << ( trunc_ln347_39_fu_632_p1 );

    SC_METHOD(thread_select_ln1494_73_fu_692_p3);
    sensitive << ( or_ln1494_9_fu_686_p2 );
    sensitive << ( select_ln1494_18_fu_678_p3 );
    sensitive << ( trunc_ln347_40_fu_674_p1 );

    SC_METHOD(thread_select_ln1494_74_fu_734_p3);
    sensitive << ( or_ln1494_10_fu_728_p2 );
    sensitive << ( select_ln1494_20_fu_720_p3 );
    sensitive << ( trunc_ln347_41_fu_716_p1 );

    SC_METHOD(thread_select_ln1494_75_fu_776_p3);
    sensitive << ( or_ln1494_11_fu_770_p2 );
    sensitive << ( select_ln1494_22_fu_762_p3 );
    sensitive << ( trunc_ln347_42_fu_758_p1 );

    SC_METHOD(thread_select_ln1494_76_fu_818_p3);
    sensitive << ( or_ln1494_12_fu_812_p2 );
    sensitive << ( select_ln1494_24_fu_804_p3 );
    sensitive << ( trunc_ln347_43_fu_800_p1 );

    SC_METHOD(thread_select_ln1494_77_fu_860_p3);
    sensitive << ( or_ln1494_13_fu_854_p2 );
    sensitive << ( select_ln1494_26_fu_846_p3 );
    sensitive << ( trunc_ln347_44_fu_842_p1 );

    SC_METHOD(thread_select_ln1494_78_fu_902_p3);
    sensitive << ( or_ln1494_14_fu_896_p2 );
    sensitive << ( select_ln1494_28_fu_888_p3 );
    sensitive << ( trunc_ln347_45_fu_884_p1 );

    SC_METHOD(thread_select_ln1494_79_fu_944_p3);
    sensitive << ( or_ln1494_15_fu_938_p2 );
    sensitive << ( select_ln1494_30_fu_930_p3 );
    sensitive << ( trunc_ln347_46_fu_926_p1 );

    SC_METHOD(thread_select_ln1494_80_fu_986_p3);
    sensitive << ( or_ln1494_16_fu_980_p2 );
    sensitive << ( select_ln1494_32_fu_972_p3 );
    sensitive << ( trunc_ln347_47_fu_968_p1 );

    SC_METHOD(thread_select_ln1494_81_fu_1028_p3);
    sensitive << ( or_ln1494_17_fu_1022_p2 );
    sensitive << ( select_ln1494_34_fu_1014_p3 );
    sensitive << ( trunc_ln347_48_fu_1010_p1 );

    SC_METHOD(thread_select_ln1494_82_fu_1070_p3);
    sensitive << ( or_ln1494_18_fu_1064_p2 );
    sensitive << ( select_ln1494_36_fu_1056_p3 );
    sensitive << ( trunc_ln347_49_fu_1052_p1 );

    SC_METHOD(thread_select_ln1494_83_fu_1112_p3);
    sensitive << ( or_ln1494_19_fu_1106_p2 );
    sensitive << ( select_ln1494_38_fu_1098_p3 );
    sensitive << ( trunc_ln347_50_fu_1094_p1 );

    SC_METHOD(thread_select_ln1494_84_fu_1154_p3);
    sensitive << ( or_ln1494_20_fu_1148_p2 );
    sensitive << ( select_ln1494_40_fu_1140_p3 );
    sensitive << ( trunc_ln347_51_fu_1136_p1 );

    SC_METHOD(thread_select_ln1494_85_fu_1196_p3);
    sensitive << ( or_ln1494_21_fu_1190_p2 );
    sensitive << ( select_ln1494_42_fu_1182_p3 );
    sensitive << ( trunc_ln347_52_fu_1178_p1 );

    SC_METHOD(thread_select_ln1494_86_fu_1238_p3);
    sensitive << ( or_ln1494_22_fu_1232_p2 );
    sensitive << ( select_ln1494_44_fu_1224_p3 );
    sensitive << ( trunc_ln347_53_fu_1220_p1 );

    SC_METHOD(thread_select_ln1494_87_fu_1280_p3);
    sensitive << ( or_ln1494_23_fu_1274_p2 );
    sensitive << ( select_ln1494_46_fu_1266_p3 );
    sensitive << ( trunc_ln347_54_fu_1262_p1 );

    SC_METHOD(thread_select_ln1494_88_fu_1322_p3);
    sensitive << ( or_ln1494_24_fu_1316_p2 );
    sensitive << ( select_ln1494_48_fu_1308_p3 );
    sensitive << ( trunc_ln347_55_fu_1304_p1 );

    SC_METHOD(thread_select_ln1494_89_fu_1364_p3);
    sensitive << ( or_ln1494_25_fu_1358_p2 );
    sensitive << ( select_ln1494_50_fu_1350_p3 );
    sensitive << ( trunc_ln347_56_fu_1346_p1 );

    SC_METHOD(thread_select_ln1494_8_fu_468_p3);
    sensitive << ( icmp_ln1494_4_fu_452_p2 );

    SC_METHOD(thread_select_ln1494_90_fu_1406_p3);
    sensitive << ( or_ln1494_26_fu_1400_p2 );
    sensitive << ( select_ln1494_52_fu_1392_p3 );
    sensitive << ( trunc_ln347_57_fu_1388_p1 );

    SC_METHOD(thread_select_ln1494_91_fu_1448_p3);
    sensitive << ( or_ln1494_27_fu_1442_p2 );
    sensitive << ( select_ln1494_54_fu_1434_p3 );
    sensitive << ( trunc_ln347_58_fu_1430_p1 );

    SC_METHOD(thread_select_ln1494_92_fu_1490_p3);
    sensitive << ( or_ln1494_28_fu_1484_p2 );
    sensitive << ( select_ln1494_56_fu_1476_p3 );
    sensitive << ( trunc_ln347_59_fu_1472_p1 );

    SC_METHOD(thread_select_ln1494_93_fu_1532_p3);
    sensitive << ( or_ln1494_29_fu_1526_p2 );
    sensitive << ( select_ln1494_58_fu_1518_p3 );
    sensitive << ( trunc_ln347_60_fu_1514_p1 );

    SC_METHOD(thread_select_ln1494_94_fu_1574_p3);
    sensitive << ( or_ln1494_30_fu_1568_p2 );
    sensitive << ( select_ln1494_60_fu_1560_p3 );
    sensitive << ( trunc_ln347_61_fu_1556_p1 );

    SC_METHOD(thread_select_ln1494_95_fu_1616_p3);
    sensitive << ( or_ln1494_31_fu_1610_p2 );
    sensitive << ( select_ln1494_62_fu_1602_p3 );
    sensitive << ( trunc_ln347_62_fu_1598_p1 );

    SC_METHOD(thread_select_ln1494_fu_300_p3);
    sensitive << ( icmp_ln1494_fu_284_p2 );

    SC_METHOD(thread_sext_ln1494_10_fu_742_p1);
    sensitive << ( select_ln1494_74_fu_734_p3 );

    SC_METHOD(thread_sext_ln1494_11_fu_784_p1);
    sensitive << ( select_ln1494_75_fu_776_p3 );

    SC_METHOD(thread_sext_ln1494_12_fu_826_p1);
    sensitive << ( select_ln1494_76_fu_818_p3 );

    SC_METHOD(thread_sext_ln1494_13_fu_868_p1);
    sensitive << ( select_ln1494_77_fu_860_p3 );

    SC_METHOD(thread_sext_ln1494_14_fu_910_p1);
    sensitive << ( select_ln1494_78_fu_902_p3 );

    SC_METHOD(thread_sext_ln1494_15_fu_952_p1);
    sensitive << ( select_ln1494_79_fu_944_p3 );

    SC_METHOD(thread_sext_ln1494_16_fu_994_p1);
    sensitive << ( select_ln1494_80_fu_986_p3 );

    SC_METHOD(thread_sext_ln1494_17_fu_1036_p1);
    sensitive << ( select_ln1494_81_fu_1028_p3 );

    SC_METHOD(thread_sext_ln1494_18_fu_1078_p1);
    sensitive << ( select_ln1494_82_fu_1070_p3 );

    SC_METHOD(thread_sext_ln1494_19_fu_1120_p1);
    sensitive << ( select_ln1494_83_fu_1112_p3 );

    SC_METHOD(thread_sext_ln1494_1_fu_364_p1);
    sensitive << ( select_ln1494_65_fu_356_p3 );

    SC_METHOD(thread_sext_ln1494_20_fu_1162_p1);
    sensitive << ( select_ln1494_84_fu_1154_p3 );

    SC_METHOD(thread_sext_ln1494_21_fu_1204_p1);
    sensitive << ( select_ln1494_85_fu_1196_p3 );

    SC_METHOD(thread_sext_ln1494_22_fu_1246_p1);
    sensitive << ( select_ln1494_86_fu_1238_p3 );

    SC_METHOD(thread_sext_ln1494_23_fu_1288_p1);
    sensitive << ( select_ln1494_87_fu_1280_p3 );

    SC_METHOD(thread_sext_ln1494_24_fu_1330_p1);
    sensitive << ( select_ln1494_88_fu_1322_p3 );

    SC_METHOD(thread_sext_ln1494_25_fu_1372_p1);
    sensitive << ( select_ln1494_89_fu_1364_p3 );

    SC_METHOD(thread_sext_ln1494_26_fu_1414_p1);
    sensitive << ( select_ln1494_90_fu_1406_p3 );

    SC_METHOD(thread_sext_ln1494_27_fu_1456_p1);
    sensitive << ( select_ln1494_91_fu_1448_p3 );

    SC_METHOD(thread_sext_ln1494_28_fu_1498_p1);
    sensitive << ( select_ln1494_92_fu_1490_p3 );

    SC_METHOD(thread_sext_ln1494_29_fu_1540_p1);
    sensitive << ( select_ln1494_93_fu_1532_p3 );

    SC_METHOD(thread_sext_ln1494_2_fu_406_p1);
    sensitive << ( select_ln1494_66_fu_398_p3 );

    SC_METHOD(thread_sext_ln1494_30_fu_1582_p1);
    sensitive << ( select_ln1494_94_fu_1574_p3 );

    SC_METHOD(thread_sext_ln1494_3_fu_448_p1);
    sensitive << ( select_ln1494_67_fu_440_p3 );

    SC_METHOD(thread_sext_ln1494_4_fu_490_p1);
    sensitive << ( select_ln1494_68_fu_482_p3 );

    SC_METHOD(thread_sext_ln1494_5_fu_532_p1);
    sensitive << ( select_ln1494_69_fu_524_p3 );

    SC_METHOD(thread_sext_ln1494_6_fu_574_p1);
    sensitive << ( select_ln1494_70_fu_566_p3 );

    SC_METHOD(thread_sext_ln1494_7_fu_616_p1);
    sensitive << ( select_ln1494_71_fu_608_p3 );

    SC_METHOD(thread_sext_ln1494_8_fu_658_p1);
    sensitive << ( select_ln1494_72_fu_650_p3 );

    SC_METHOD(thread_sext_ln1494_9_fu_700_p1);
    sensitive << ( select_ln1494_73_fu_692_p3 );

    SC_METHOD(thread_sext_ln1494_fu_322_p1);
    sensitive << ( select_ln1494_64_fu_314_p3 );

    SC_METHOD(thread_sext_ln331_fu_1624_p1);
    sensitive << ( select_ln1494_95_fu_1616_p3 );

    SC_METHOD(thread_trunc_ln347_32_fu_338_p1);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_trunc_ln347_33_fu_380_p1);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_trunc_ln347_34_fu_422_p1);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_trunc_ln347_35_fu_464_p1);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_trunc_ln347_36_fu_506_p1);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_trunc_ln347_37_fu_548_p1);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_trunc_ln347_38_fu_590_p1);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_trunc_ln347_39_fu_632_p1);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_trunc_ln347_40_fu_674_p1);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_trunc_ln347_41_fu_716_p1);
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_trunc_ln347_42_fu_758_p1);
    sensitive << ( data_11_V_read );

    SC_METHOD(thread_trunc_ln347_43_fu_800_p1);
    sensitive << ( data_12_V_read );

    SC_METHOD(thread_trunc_ln347_44_fu_842_p1);
    sensitive << ( data_13_V_read );

    SC_METHOD(thread_trunc_ln347_45_fu_884_p1);
    sensitive << ( data_14_V_read );

    SC_METHOD(thread_trunc_ln347_46_fu_926_p1);
    sensitive << ( data_15_V_read );

    SC_METHOD(thread_trunc_ln347_47_fu_968_p1);
    sensitive << ( data_16_V_read );

    SC_METHOD(thread_trunc_ln347_48_fu_1010_p1);
    sensitive << ( data_17_V_read );

    SC_METHOD(thread_trunc_ln347_49_fu_1052_p1);
    sensitive << ( data_18_V_read );

    SC_METHOD(thread_trunc_ln347_50_fu_1094_p1);
    sensitive << ( data_19_V_read );

    SC_METHOD(thread_trunc_ln347_51_fu_1136_p1);
    sensitive << ( data_20_V_read );

    SC_METHOD(thread_trunc_ln347_52_fu_1178_p1);
    sensitive << ( data_21_V_read );

    SC_METHOD(thread_trunc_ln347_53_fu_1220_p1);
    sensitive << ( data_22_V_read );

    SC_METHOD(thread_trunc_ln347_54_fu_1262_p1);
    sensitive << ( data_23_V_read );

    SC_METHOD(thread_trunc_ln347_55_fu_1304_p1);
    sensitive << ( data_24_V_read );

    SC_METHOD(thread_trunc_ln347_56_fu_1346_p1);
    sensitive << ( data_25_V_read );

    SC_METHOD(thread_trunc_ln347_57_fu_1388_p1);
    sensitive << ( data_26_V_read );

    SC_METHOD(thread_trunc_ln347_58_fu_1430_p1);
    sensitive << ( data_27_V_read );

    SC_METHOD(thread_trunc_ln347_59_fu_1472_p1);
    sensitive << ( data_28_V_read );

    SC_METHOD(thread_trunc_ln347_60_fu_1514_p1);
    sensitive << ( data_29_V_read );

    SC_METHOD(thread_trunc_ln347_61_fu_1556_p1);
    sensitive << ( data_30_V_read );

    SC_METHOD(thread_trunc_ln347_62_fu_1598_p1);
    sensitive << ( data_31_V_read );

    SC_METHOD(thread_trunc_ln347_fu_296_p1);
    sensitive << ( data_0_V_read );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "hard_tanh_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, data_9_V_read, "(port)data_9_V_read");
    sc_trace(mVcdFile, data_10_V_read, "(port)data_10_V_read");
    sc_trace(mVcdFile, data_11_V_read, "(port)data_11_V_read");
    sc_trace(mVcdFile, data_12_V_read, "(port)data_12_V_read");
    sc_trace(mVcdFile, data_13_V_read, "(port)data_13_V_read");
    sc_trace(mVcdFile, data_14_V_read, "(port)data_14_V_read");
    sc_trace(mVcdFile, data_15_V_read, "(port)data_15_V_read");
    sc_trace(mVcdFile, data_16_V_read, "(port)data_16_V_read");
    sc_trace(mVcdFile, data_17_V_read, "(port)data_17_V_read");
    sc_trace(mVcdFile, data_18_V_read, "(port)data_18_V_read");
    sc_trace(mVcdFile, data_19_V_read, "(port)data_19_V_read");
    sc_trace(mVcdFile, data_20_V_read, "(port)data_20_V_read");
    sc_trace(mVcdFile, data_21_V_read, "(port)data_21_V_read");
    sc_trace(mVcdFile, data_22_V_read, "(port)data_22_V_read");
    sc_trace(mVcdFile, data_23_V_read, "(port)data_23_V_read");
    sc_trace(mVcdFile, data_24_V_read, "(port)data_24_V_read");
    sc_trace(mVcdFile, data_25_V_read, "(port)data_25_V_read");
    sc_trace(mVcdFile, data_26_V_read, "(port)data_26_V_read");
    sc_trace(mVcdFile, data_27_V_read, "(port)data_27_V_read");
    sc_trace(mVcdFile, data_28_V_read, "(port)data_28_V_read");
    sc_trace(mVcdFile, data_29_V_read, "(port)data_29_V_read");
    sc_trace(mVcdFile, data_30_V_read, "(port)data_30_V_read");
    sc_trace(mVcdFile, data_31_V_read, "(port)data_31_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_return_8, "(port)ap_return_8");
    sc_trace(mVcdFile, ap_return_9, "(port)ap_return_9");
    sc_trace(mVcdFile, ap_return_10, "(port)ap_return_10");
    sc_trace(mVcdFile, ap_return_11, "(port)ap_return_11");
    sc_trace(mVcdFile, ap_return_12, "(port)ap_return_12");
    sc_trace(mVcdFile, ap_return_13, "(port)ap_return_13");
    sc_trace(mVcdFile, ap_return_14, "(port)ap_return_14");
    sc_trace(mVcdFile, ap_return_15, "(port)ap_return_15");
    sc_trace(mVcdFile, ap_return_16, "(port)ap_return_16");
    sc_trace(mVcdFile, ap_return_17, "(port)ap_return_17");
    sc_trace(mVcdFile, ap_return_18, "(port)ap_return_18");
    sc_trace(mVcdFile, ap_return_19, "(port)ap_return_19");
    sc_trace(mVcdFile, ap_return_20, "(port)ap_return_20");
    sc_trace(mVcdFile, ap_return_21, "(port)ap_return_21");
    sc_trace(mVcdFile, ap_return_22, "(port)ap_return_22");
    sc_trace(mVcdFile, ap_return_23, "(port)ap_return_23");
    sc_trace(mVcdFile, ap_return_24, "(port)ap_return_24");
    sc_trace(mVcdFile, ap_return_25, "(port)ap_return_25");
    sc_trace(mVcdFile, ap_return_26, "(port)ap_return_26");
    sc_trace(mVcdFile, ap_return_27, "(port)ap_return_27");
    sc_trace(mVcdFile, ap_return_28, "(port)ap_return_28");
    sc_trace(mVcdFile, ap_return_29, "(port)ap_return_29");
    sc_trace(mVcdFile, ap_return_30, "(port)ap_return_30");
    sc_trace(mVcdFile, ap_return_31, "(port)ap_return_31");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, icmp_ln1494_fu_284_p2, "icmp_ln1494_fu_284_p2");
    sc_trace(mVcdFile, icmp_ln1495_fu_290_p2, "icmp_ln1495_fu_290_p2");
    sc_trace(mVcdFile, or_ln1494_fu_308_p2, "or_ln1494_fu_308_p2");
    sc_trace(mVcdFile, select_ln1494_fu_300_p3, "select_ln1494_fu_300_p3");
    sc_trace(mVcdFile, trunc_ln347_fu_296_p1, "trunc_ln347_fu_296_p1");
    sc_trace(mVcdFile, select_ln1494_64_fu_314_p3, "select_ln1494_64_fu_314_p3");
    sc_trace(mVcdFile, icmp_ln1494_1_fu_326_p2, "icmp_ln1494_1_fu_326_p2");
    sc_trace(mVcdFile, icmp_ln1495_1_fu_332_p2, "icmp_ln1495_1_fu_332_p2");
    sc_trace(mVcdFile, or_ln1494_1_fu_350_p2, "or_ln1494_1_fu_350_p2");
    sc_trace(mVcdFile, select_ln1494_2_fu_342_p3, "select_ln1494_2_fu_342_p3");
    sc_trace(mVcdFile, trunc_ln347_32_fu_338_p1, "trunc_ln347_32_fu_338_p1");
    sc_trace(mVcdFile, select_ln1494_65_fu_356_p3, "select_ln1494_65_fu_356_p3");
    sc_trace(mVcdFile, icmp_ln1494_2_fu_368_p2, "icmp_ln1494_2_fu_368_p2");
    sc_trace(mVcdFile, icmp_ln1495_2_fu_374_p2, "icmp_ln1495_2_fu_374_p2");
    sc_trace(mVcdFile, or_ln1494_2_fu_392_p2, "or_ln1494_2_fu_392_p2");
    sc_trace(mVcdFile, select_ln1494_4_fu_384_p3, "select_ln1494_4_fu_384_p3");
    sc_trace(mVcdFile, trunc_ln347_33_fu_380_p1, "trunc_ln347_33_fu_380_p1");
    sc_trace(mVcdFile, select_ln1494_66_fu_398_p3, "select_ln1494_66_fu_398_p3");
    sc_trace(mVcdFile, icmp_ln1494_3_fu_410_p2, "icmp_ln1494_3_fu_410_p2");
    sc_trace(mVcdFile, icmp_ln1495_3_fu_416_p2, "icmp_ln1495_3_fu_416_p2");
    sc_trace(mVcdFile, or_ln1494_3_fu_434_p2, "or_ln1494_3_fu_434_p2");
    sc_trace(mVcdFile, select_ln1494_6_fu_426_p3, "select_ln1494_6_fu_426_p3");
    sc_trace(mVcdFile, trunc_ln347_34_fu_422_p1, "trunc_ln347_34_fu_422_p1");
    sc_trace(mVcdFile, select_ln1494_67_fu_440_p3, "select_ln1494_67_fu_440_p3");
    sc_trace(mVcdFile, icmp_ln1494_4_fu_452_p2, "icmp_ln1494_4_fu_452_p2");
    sc_trace(mVcdFile, icmp_ln1495_4_fu_458_p2, "icmp_ln1495_4_fu_458_p2");
    sc_trace(mVcdFile, or_ln1494_4_fu_476_p2, "or_ln1494_4_fu_476_p2");
    sc_trace(mVcdFile, select_ln1494_8_fu_468_p3, "select_ln1494_8_fu_468_p3");
    sc_trace(mVcdFile, trunc_ln347_35_fu_464_p1, "trunc_ln347_35_fu_464_p1");
    sc_trace(mVcdFile, select_ln1494_68_fu_482_p3, "select_ln1494_68_fu_482_p3");
    sc_trace(mVcdFile, icmp_ln1494_5_fu_494_p2, "icmp_ln1494_5_fu_494_p2");
    sc_trace(mVcdFile, icmp_ln1495_5_fu_500_p2, "icmp_ln1495_5_fu_500_p2");
    sc_trace(mVcdFile, or_ln1494_5_fu_518_p2, "or_ln1494_5_fu_518_p2");
    sc_trace(mVcdFile, select_ln1494_10_fu_510_p3, "select_ln1494_10_fu_510_p3");
    sc_trace(mVcdFile, trunc_ln347_36_fu_506_p1, "trunc_ln347_36_fu_506_p1");
    sc_trace(mVcdFile, select_ln1494_69_fu_524_p3, "select_ln1494_69_fu_524_p3");
    sc_trace(mVcdFile, icmp_ln1494_6_fu_536_p2, "icmp_ln1494_6_fu_536_p2");
    sc_trace(mVcdFile, icmp_ln1495_6_fu_542_p2, "icmp_ln1495_6_fu_542_p2");
    sc_trace(mVcdFile, or_ln1494_6_fu_560_p2, "or_ln1494_6_fu_560_p2");
    sc_trace(mVcdFile, select_ln1494_12_fu_552_p3, "select_ln1494_12_fu_552_p3");
    sc_trace(mVcdFile, trunc_ln347_37_fu_548_p1, "trunc_ln347_37_fu_548_p1");
    sc_trace(mVcdFile, select_ln1494_70_fu_566_p3, "select_ln1494_70_fu_566_p3");
    sc_trace(mVcdFile, icmp_ln1494_7_fu_578_p2, "icmp_ln1494_7_fu_578_p2");
    sc_trace(mVcdFile, icmp_ln1495_7_fu_584_p2, "icmp_ln1495_7_fu_584_p2");
    sc_trace(mVcdFile, or_ln1494_7_fu_602_p2, "or_ln1494_7_fu_602_p2");
    sc_trace(mVcdFile, select_ln1494_14_fu_594_p3, "select_ln1494_14_fu_594_p3");
    sc_trace(mVcdFile, trunc_ln347_38_fu_590_p1, "trunc_ln347_38_fu_590_p1");
    sc_trace(mVcdFile, select_ln1494_71_fu_608_p3, "select_ln1494_71_fu_608_p3");
    sc_trace(mVcdFile, icmp_ln1494_8_fu_620_p2, "icmp_ln1494_8_fu_620_p2");
    sc_trace(mVcdFile, icmp_ln1495_8_fu_626_p2, "icmp_ln1495_8_fu_626_p2");
    sc_trace(mVcdFile, or_ln1494_8_fu_644_p2, "or_ln1494_8_fu_644_p2");
    sc_trace(mVcdFile, select_ln1494_16_fu_636_p3, "select_ln1494_16_fu_636_p3");
    sc_trace(mVcdFile, trunc_ln347_39_fu_632_p1, "trunc_ln347_39_fu_632_p1");
    sc_trace(mVcdFile, select_ln1494_72_fu_650_p3, "select_ln1494_72_fu_650_p3");
    sc_trace(mVcdFile, icmp_ln1494_9_fu_662_p2, "icmp_ln1494_9_fu_662_p2");
    sc_trace(mVcdFile, icmp_ln1495_9_fu_668_p2, "icmp_ln1495_9_fu_668_p2");
    sc_trace(mVcdFile, or_ln1494_9_fu_686_p2, "or_ln1494_9_fu_686_p2");
    sc_trace(mVcdFile, select_ln1494_18_fu_678_p3, "select_ln1494_18_fu_678_p3");
    sc_trace(mVcdFile, trunc_ln347_40_fu_674_p1, "trunc_ln347_40_fu_674_p1");
    sc_trace(mVcdFile, select_ln1494_73_fu_692_p3, "select_ln1494_73_fu_692_p3");
    sc_trace(mVcdFile, icmp_ln1494_10_fu_704_p2, "icmp_ln1494_10_fu_704_p2");
    sc_trace(mVcdFile, icmp_ln1495_10_fu_710_p2, "icmp_ln1495_10_fu_710_p2");
    sc_trace(mVcdFile, or_ln1494_10_fu_728_p2, "or_ln1494_10_fu_728_p2");
    sc_trace(mVcdFile, select_ln1494_20_fu_720_p3, "select_ln1494_20_fu_720_p3");
    sc_trace(mVcdFile, trunc_ln347_41_fu_716_p1, "trunc_ln347_41_fu_716_p1");
    sc_trace(mVcdFile, select_ln1494_74_fu_734_p3, "select_ln1494_74_fu_734_p3");
    sc_trace(mVcdFile, icmp_ln1494_11_fu_746_p2, "icmp_ln1494_11_fu_746_p2");
    sc_trace(mVcdFile, icmp_ln1495_11_fu_752_p2, "icmp_ln1495_11_fu_752_p2");
    sc_trace(mVcdFile, or_ln1494_11_fu_770_p2, "or_ln1494_11_fu_770_p2");
    sc_trace(mVcdFile, select_ln1494_22_fu_762_p3, "select_ln1494_22_fu_762_p3");
    sc_trace(mVcdFile, trunc_ln347_42_fu_758_p1, "trunc_ln347_42_fu_758_p1");
    sc_trace(mVcdFile, select_ln1494_75_fu_776_p3, "select_ln1494_75_fu_776_p3");
    sc_trace(mVcdFile, icmp_ln1494_12_fu_788_p2, "icmp_ln1494_12_fu_788_p2");
    sc_trace(mVcdFile, icmp_ln1495_12_fu_794_p2, "icmp_ln1495_12_fu_794_p2");
    sc_trace(mVcdFile, or_ln1494_12_fu_812_p2, "or_ln1494_12_fu_812_p2");
    sc_trace(mVcdFile, select_ln1494_24_fu_804_p3, "select_ln1494_24_fu_804_p3");
    sc_trace(mVcdFile, trunc_ln347_43_fu_800_p1, "trunc_ln347_43_fu_800_p1");
    sc_trace(mVcdFile, select_ln1494_76_fu_818_p3, "select_ln1494_76_fu_818_p3");
    sc_trace(mVcdFile, icmp_ln1494_13_fu_830_p2, "icmp_ln1494_13_fu_830_p2");
    sc_trace(mVcdFile, icmp_ln1495_13_fu_836_p2, "icmp_ln1495_13_fu_836_p2");
    sc_trace(mVcdFile, or_ln1494_13_fu_854_p2, "or_ln1494_13_fu_854_p2");
    sc_trace(mVcdFile, select_ln1494_26_fu_846_p3, "select_ln1494_26_fu_846_p3");
    sc_trace(mVcdFile, trunc_ln347_44_fu_842_p1, "trunc_ln347_44_fu_842_p1");
    sc_trace(mVcdFile, select_ln1494_77_fu_860_p3, "select_ln1494_77_fu_860_p3");
    sc_trace(mVcdFile, icmp_ln1494_14_fu_872_p2, "icmp_ln1494_14_fu_872_p2");
    sc_trace(mVcdFile, icmp_ln1495_14_fu_878_p2, "icmp_ln1495_14_fu_878_p2");
    sc_trace(mVcdFile, or_ln1494_14_fu_896_p2, "or_ln1494_14_fu_896_p2");
    sc_trace(mVcdFile, select_ln1494_28_fu_888_p3, "select_ln1494_28_fu_888_p3");
    sc_trace(mVcdFile, trunc_ln347_45_fu_884_p1, "trunc_ln347_45_fu_884_p1");
    sc_trace(mVcdFile, select_ln1494_78_fu_902_p3, "select_ln1494_78_fu_902_p3");
    sc_trace(mVcdFile, icmp_ln1494_15_fu_914_p2, "icmp_ln1494_15_fu_914_p2");
    sc_trace(mVcdFile, icmp_ln1495_15_fu_920_p2, "icmp_ln1495_15_fu_920_p2");
    sc_trace(mVcdFile, or_ln1494_15_fu_938_p2, "or_ln1494_15_fu_938_p2");
    sc_trace(mVcdFile, select_ln1494_30_fu_930_p3, "select_ln1494_30_fu_930_p3");
    sc_trace(mVcdFile, trunc_ln347_46_fu_926_p1, "trunc_ln347_46_fu_926_p1");
    sc_trace(mVcdFile, select_ln1494_79_fu_944_p3, "select_ln1494_79_fu_944_p3");
    sc_trace(mVcdFile, icmp_ln1494_16_fu_956_p2, "icmp_ln1494_16_fu_956_p2");
    sc_trace(mVcdFile, icmp_ln1495_16_fu_962_p2, "icmp_ln1495_16_fu_962_p2");
    sc_trace(mVcdFile, or_ln1494_16_fu_980_p2, "or_ln1494_16_fu_980_p2");
    sc_trace(mVcdFile, select_ln1494_32_fu_972_p3, "select_ln1494_32_fu_972_p3");
    sc_trace(mVcdFile, trunc_ln347_47_fu_968_p1, "trunc_ln347_47_fu_968_p1");
    sc_trace(mVcdFile, select_ln1494_80_fu_986_p3, "select_ln1494_80_fu_986_p3");
    sc_trace(mVcdFile, icmp_ln1494_17_fu_998_p2, "icmp_ln1494_17_fu_998_p2");
    sc_trace(mVcdFile, icmp_ln1495_17_fu_1004_p2, "icmp_ln1495_17_fu_1004_p2");
    sc_trace(mVcdFile, or_ln1494_17_fu_1022_p2, "or_ln1494_17_fu_1022_p2");
    sc_trace(mVcdFile, select_ln1494_34_fu_1014_p3, "select_ln1494_34_fu_1014_p3");
    sc_trace(mVcdFile, trunc_ln347_48_fu_1010_p1, "trunc_ln347_48_fu_1010_p1");
    sc_trace(mVcdFile, select_ln1494_81_fu_1028_p3, "select_ln1494_81_fu_1028_p3");
    sc_trace(mVcdFile, icmp_ln1494_18_fu_1040_p2, "icmp_ln1494_18_fu_1040_p2");
    sc_trace(mVcdFile, icmp_ln1495_18_fu_1046_p2, "icmp_ln1495_18_fu_1046_p2");
    sc_trace(mVcdFile, or_ln1494_18_fu_1064_p2, "or_ln1494_18_fu_1064_p2");
    sc_trace(mVcdFile, select_ln1494_36_fu_1056_p3, "select_ln1494_36_fu_1056_p3");
    sc_trace(mVcdFile, trunc_ln347_49_fu_1052_p1, "trunc_ln347_49_fu_1052_p1");
    sc_trace(mVcdFile, select_ln1494_82_fu_1070_p3, "select_ln1494_82_fu_1070_p3");
    sc_trace(mVcdFile, icmp_ln1494_19_fu_1082_p2, "icmp_ln1494_19_fu_1082_p2");
    sc_trace(mVcdFile, icmp_ln1495_19_fu_1088_p2, "icmp_ln1495_19_fu_1088_p2");
    sc_trace(mVcdFile, or_ln1494_19_fu_1106_p2, "or_ln1494_19_fu_1106_p2");
    sc_trace(mVcdFile, select_ln1494_38_fu_1098_p3, "select_ln1494_38_fu_1098_p3");
    sc_trace(mVcdFile, trunc_ln347_50_fu_1094_p1, "trunc_ln347_50_fu_1094_p1");
    sc_trace(mVcdFile, select_ln1494_83_fu_1112_p3, "select_ln1494_83_fu_1112_p3");
    sc_trace(mVcdFile, icmp_ln1494_20_fu_1124_p2, "icmp_ln1494_20_fu_1124_p2");
    sc_trace(mVcdFile, icmp_ln1495_20_fu_1130_p2, "icmp_ln1495_20_fu_1130_p2");
    sc_trace(mVcdFile, or_ln1494_20_fu_1148_p2, "or_ln1494_20_fu_1148_p2");
    sc_trace(mVcdFile, select_ln1494_40_fu_1140_p3, "select_ln1494_40_fu_1140_p3");
    sc_trace(mVcdFile, trunc_ln347_51_fu_1136_p1, "trunc_ln347_51_fu_1136_p1");
    sc_trace(mVcdFile, select_ln1494_84_fu_1154_p3, "select_ln1494_84_fu_1154_p3");
    sc_trace(mVcdFile, icmp_ln1494_21_fu_1166_p2, "icmp_ln1494_21_fu_1166_p2");
    sc_trace(mVcdFile, icmp_ln1495_21_fu_1172_p2, "icmp_ln1495_21_fu_1172_p2");
    sc_trace(mVcdFile, or_ln1494_21_fu_1190_p2, "or_ln1494_21_fu_1190_p2");
    sc_trace(mVcdFile, select_ln1494_42_fu_1182_p3, "select_ln1494_42_fu_1182_p3");
    sc_trace(mVcdFile, trunc_ln347_52_fu_1178_p1, "trunc_ln347_52_fu_1178_p1");
    sc_trace(mVcdFile, select_ln1494_85_fu_1196_p3, "select_ln1494_85_fu_1196_p3");
    sc_trace(mVcdFile, icmp_ln1494_22_fu_1208_p2, "icmp_ln1494_22_fu_1208_p2");
    sc_trace(mVcdFile, icmp_ln1495_22_fu_1214_p2, "icmp_ln1495_22_fu_1214_p2");
    sc_trace(mVcdFile, or_ln1494_22_fu_1232_p2, "or_ln1494_22_fu_1232_p2");
    sc_trace(mVcdFile, select_ln1494_44_fu_1224_p3, "select_ln1494_44_fu_1224_p3");
    sc_trace(mVcdFile, trunc_ln347_53_fu_1220_p1, "trunc_ln347_53_fu_1220_p1");
    sc_trace(mVcdFile, select_ln1494_86_fu_1238_p3, "select_ln1494_86_fu_1238_p3");
    sc_trace(mVcdFile, icmp_ln1494_23_fu_1250_p2, "icmp_ln1494_23_fu_1250_p2");
    sc_trace(mVcdFile, icmp_ln1495_23_fu_1256_p2, "icmp_ln1495_23_fu_1256_p2");
    sc_trace(mVcdFile, or_ln1494_23_fu_1274_p2, "or_ln1494_23_fu_1274_p2");
    sc_trace(mVcdFile, select_ln1494_46_fu_1266_p3, "select_ln1494_46_fu_1266_p3");
    sc_trace(mVcdFile, trunc_ln347_54_fu_1262_p1, "trunc_ln347_54_fu_1262_p1");
    sc_trace(mVcdFile, select_ln1494_87_fu_1280_p3, "select_ln1494_87_fu_1280_p3");
    sc_trace(mVcdFile, icmp_ln1494_24_fu_1292_p2, "icmp_ln1494_24_fu_1292_p2");
    sc_trace(mVcdFile, icmp_ln1495_24_fu_1298_p2, "icmp_ln1495_24_fu_1298_p2");
    sc_trace(mVcdFile, or_ln1494_24_fu_1316_p2, "or_ln1494_24_fu_1316_p2");
    sc_trace(mVcdFile, select_ln1494_48_fu_1308_p3, "select_ln1494_48_fu_1308_p3");
    sc_trace(mVcdFile, trunc_ln347_55_fu_1304_p1, "trunc_ln347_55_fu_1304_p1");
    sc_trace(mVcdFile, select_ln1494_88_fu_1322_p3, "select_ln1494_88_fu_1322_p3");
    sc_trace(mVcdFile, icmp_ln1494_25_fu_1334_p2, "icmp_ln1494_25_fu_1334_p2");
    sc_trace(mVcdFile, icmp_ln1495_25_fu_1340_p2, "icmp_ln1495_25_fu_1340_p2");
    sc_trace(mVcdFile, or_ln1494_25_fu_1358_p2, "or_ln1494_25_fu_1358_p2");
    sc_trace(mVcdFile, select_ln1494_50_fu_1350_p3, "select_ln1494_50_fu_1350_p3");
    sc_trace(mVcdFile, trunc_ln347_56_fu_1346_p1, "trunc_ln347_56_fu_1346_p1");
    sc_trace(mVcdFile, select_ln1494_89_fu_1364_p3, "select_ln1494_89_fu_1364_p3");
    sc_trace(mVcdFile, icmp_ln1494_26_fu_1376_p2, "icmp_ln1494_26_fu_1376_p2");
    sc_trace(mVcdFile, icmp_ln1495_26_fu_1382_p2, "icmp_ln1495_26_fu_1382_p2");
    sc_trace(mVcdFile, or_ln1494_26_fu_1400_p2, "or_ln1494_26_fu_1400_p2");
    sc_trace(mVcdFile, select_ln1494_52_fu_1392_p3, "select_ln1494_52_fu_1392_p3");
    sc_trace(mVcdFile, trunc_ln347_57_fu_1388_p1, "trunc_ln347_57_fu_1388_p1");
    sc_trace(mVcdFile, select_ln1494_90_fu_1406_p3, "select_ln1494_90_fu_1406_p3");
    sc_trace(mVcdFile, icmp_ln1494_27_fu_1418_p2, "icmp_ln1494_27_fu_1418_p2");
    sc_trace(mVcdFile, icmp_ln1495_27_fu_1424_p2, "icmp_ln1495_27_fu_1424_p2");
    sc_trace(mVcdFile, or_ln1494_27_fu_1442_p2, "or_ln1494_27_fu_1442_p2");
    sc_trace(mVcdFile, select_ln1494_54_fu_1434_p3, "select_ln1494_54_fu_1434_p3");
    sc_trace(mVcdFile, trunc_ln347_58_fu_1430_p1, "trunc_ln347_58_fu_1430_p1");
    sc_trace(mVcdFile, select_ln1494_91_fu_1448_p3, "select_ln1494_91_fu_1448_p3");
    sc_trace(mVcdFile, icmp_ln1494_28_fu_1460_p2, "icmp_ln1494_28_fu_1460_p2");
    sc_trace(mVcdFile, icmp_ln1495_28_fu_1466_p2, "icmp_ln1495_28_fu_1466_p2");
    sc_trace(mVcdFile, or_ln1494_28_fu_1484_p2, "or_ln1494_28_fu_1484_p2");
    sc_trace(mVcdFile, select_ln1494_56_fu_1476_p3, "select_ln1494_56_fu_1476_p3");
    sc_trace(mVcdFile, trunc_ln347_59_fu_1472_p1, "trunc_ln347_59_fu_1472_p1");
    sc_trace(mVcdFile, select_ln1494_92_fu_1490_p3, "select_ln1494_92_fu_1490_p3");
    sc_trace(mVcdFile, icmp_ln1494_29_fu_1502_p2, "icmp_ln1494_29_fu_1502_p2");
    sc_trace(mVcdFile, icmp_ln1495_29_fu_1508_p2, "icmp_ln1495_29_fu_1508_p2");
    sc_trace(mVcdFile, or_ln1494_29_fu_1526_p2, "or_ln1494_29_fu_1526_p2");
    sc_trace(mVcdFile, select_ln1494_58_fu_1518_p3, "select_ln1494_58_fu_1518_p3");
    sc_trace(mVcdFile, trunc_ln347_60_fu_1514_p1, "trunc_ln347_60_fu_1514_p1");
    sc_trace(mVcdFile, select_ln1494_93_fu_1532_p3, "select_ln1494_93_fu_1532_p3");
    sc_trace(mVcdFile, icmp_ln1494_30_fu_1544_p2, "icmp_ln1494_30_fu_1544_p2");
    sc_trace(mVcdFile, icmp_ln1495_30_fu_1550_p2, "icmp_ln1495_30_fu_1550_p2");
    sc_trace(mVcdFile, or_ln1494_30_fu_1568_p2, "or_ln1494_30_fu_1568_p2");
    sc_trace(mVcdFile, select_ln1494_60_fu_1560_p3, "select_ln1494_60_fu_1560_p3");
    sc_trace(mVcdFile, trunc_ln347_61_fu_1556_p1, "trunc_ln347_61_fu_1556_p1");
    sc_trace(mVcdFile, select_ln1494_94_fu_1574_p3, "select_ln1494_94_fu_1574_p3");
    sc_trace(mVcdFile, icmp_ln1494_31_fu_1586_p2, "icmp_ln1494_31_fu_1586_p2");
    sc_trace(mVcdFile, icmp_ln1495_31_fu_1592_p2, "icmp_ln1495_31_fu_1592_p2");
    sc_trace(mVcdFile, or_ln1494_31_fu_1610_p2, "or_ln1494_31_fu_1610_p2");
    sc_trace(mVcdFile, select_ln1494_62_fu_1602_p3, "select_ln1494_62_fu_1602_p3");
    sc_trace(mVcdFile, trunc_ln347_62_fu_1598_p1, "trunc_ln347_62_fu_1598_p1");
    sc_trace(mVcdFile, select_ln1494_95_fu_1616_p3, "select_ln1494_95_fu_1616_p3");
    sc_trace(mVcdFile, sext_ln1494_fu_322_p1, "sext_ln1494_fu_322_p1");
    sc_trace(mVcdFile, sext_ln1494_1_fu_364_p1, "sext_ln1494_1_fu_364_p1");
    sc_trace(mVcdFile, sext_ln1494_2_fu_406_p1, "sext_ln1494_2_fu_406_p1");
    sc_trace(mVcdFile, sext_ln1494_3_fu_448_p1, "sext_ln1494_3_fu_448_p1");
    sc_trace(mVcdFile, sext_ln1494_4_fu_490_p1, "sext_ln1494_4_fu_490_p1");
    sc_trace(mVcdFile, sext_ln1494_5_fu_532_p1, "sext_ln1494_5_fu_532_p1");
    sc_trace(mVcdFile, sext_ln1494_6_fu_574_p1, "sext_ln1494_6_fu_574_p1");
    sc_trace(mVcdFile, sext_ln1494_7_fu_616_p1, "sext_ln1494_7_fu_616_p1");
    sc_trace(mVcdFile, sext_ln1494_8_fu_658_p1, "sext_ln1494_8_fu_658_p1");
    sc_trace(mVcdFile, sext_ln1494_9_fu_700_p1, "sext_ln1494_9_fu_700_p1");
    sc_trace(mVcdFile, sext_ln1494_10_fu_742_p1, "sext_ln1494_10_fu_742_p1");
    sc_trace(mVcdFile, sext_ln1494_11_fu_784_p1, "sext_ln1494_11_fu_784_p1");
    sc_trace(mVcdFile, sext_ln1494_12_fu_826_p1, "sext_ln1494_12_fu_826_p1");
    sc_trace(mVcdFile, sext_ln1494_13_fu_868_p1, "sext_ln1494_13_fu_868_p1");
    sc_trace(mVcdFile, sext_ln1494_14_fu_910_p1, "sext_ln1494_14_fu_910_p1");
    sc_trace(mVcdFile, sext_ln1494_15_fu_952_p1, "sext_ln1494_15_fu_952_p1");
    sc_trace(mVcdFile, sext_ln1494_16_fu_994_p1, "sext_ln1494_16_fu_994_p1");
    sc_trace(mVcdFile, sext_ln1494_17_fu_1036_p1, "sext_ln1494_17_fu_1036_p1");
    sc_trace(mVcdFile, sext_ln1494_18_fu_1078_p1, "sext_ln1494_18_fu_1078_p1");
    sc_trace(mVcdFile, sext_ln1494_19_fu_1120_p1, "sext_ln1494_19_fu_1120_p1");
    sc_trace(mVcdFile, sext_ln1494_20_fu_1162_p1, "sext_ln1494_20_fu_1162_p1");
    sc_trace(mVcdFile, sext_ln1494_21_fu_1204_p1, "sext_ln1494_21_fu_1204_p1");
    sc_trace(mVcdFile, sext_ln1494_22_fu_1246_p1, "sext_ln1494_22_fu_1246_p1");
    sc_trace(mVcdFile, sext_ln1494_23_fu_1288_p1, "sext_ln1494_23_fu_1288_p1");
    sc_trace(mVcdFile, sext_ln1494_24_fu_1330_p1, "sext_ln1494_24_fu_1330_p1");
    sc_trace(mVcdFile, sext_ln1494_25_fu_1372_p1, "sext_ln1494_25_fu_1372_p1");
    sc_trace(mVcdFile, sext_ln1494_26_fu_1414_p1, "sext_ln1494_26_fu_1414_p1");
    sc_trace(mVcdFile, sext_ln1494_27_fu_1456_p1, "sext_ln1494_27_fu_1456_p1");
    sc_trace(mVcdFile, sext_ln1494_28_fu_1498_p1, "sext_ln1494_28_fu_1498_p1");
    sc_trace(mVcdFile, sext_ln1494_29_fu_1540_p1, "sext_ln1494_29_fu_1540_p1");
    sc_trace(mVcdFile, sext_ln1494_30_fu_1582_p1, "sext_ln1494_30_fu_1582_p1");
    sc_trace(mVcdFile, sext_ln331_fu_1624_p1, "sext_ln331_fu_1624_p1");
#endif

    }
}

hard_tanh::~hard_tanh() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void hard_tanh::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void hard_tanh::thread_ap_return_0() {
    ap_return_0 = sext_ln1494_fu_322_p1.read();
}

void hard_tanh::thread_ap_return_1() {
    ap_return_1 = sext_ln1494_1_fu_364_p1.read();
}

void hard_tanh::thread_ap_return_10() {
    ap_return_10 = sext_ln1494_10_fu_742_p1.read();
}

void hard_tanh::thread_ap_return_11() {
    ap_return_11 = sext_ln1494_11_fu_784_p1.read();
}

void hard_tanh::thread_ap_return_12() {
    ap_return_12 = sext_ln1494_12_fu_826_p1.read();
}

void hard_tanh::thread_ap_return_13() {
    ap_return_13 = sext_ln1494_13_fu_868_p1.read();
}

void hard_tanh::thread_ap_return_14() {
    ap_return_14 = sext_ln1494_14_fu_910_p1.read();
}

void hard_tanh::thread_ap_return_15() {
    ap_return_15 = sext_ln1494_15_fu_952_p1.read();
}

void hard_tanh::thread_ap_return_16() {
    ap_return_16 = sext_ln1494_16_fu_994_p1.read();
}

void hard_tanh::thread_ap_return_17() {
    ap_return_17 = sext_ln1494_17_fu_1036_p1.read();
}

void hard_tanh::thread_ap_return_18() {
    ap_return_18 = sext_ln1494_18_fu_1078_p1.read();
}

void hard_tanh::thread_ap_return_19() {
    ap_return_19 = sext_ln1494_19_fu_1120_p1.read();
}

void hard_tanh::thread_ap_return_2() {
    ap_return_2 = sext_ln1494_2_fu_406_p1.read();
}

void hard_tanh::thread_ap_return_20() {
    ap_return_20 = sext_ln1494_20_fu_1162_p1.read();
}

void hard_tanh::thread_ap_return_21() {
    ap_return_21 = sext_ln1494_21_fu_1204_p1.read();
}

void hard_tanh::thread_ap_return_22() {
    ap_return_22 = sext_ln1494_22_fu_1246_p1.read();
}

void hard_tanh::thread_ap_return_23() {
    ap_return_23 = sext_ln1494_23_fu_1288_p1.read();
}

void hard_tanh::thread_ap_return_24() {
    ap_return_24 = sext_ln1494_24_fu_1330_p1.read();
}

void hard_tanh::thread_ap_return_25() {
    ap_return_25 = sext_ln1494_25_fu_1372_p1.read();
}

void hard_tanh::thread_ap_return_26() {
    ap_return_26 = sext_ln1494_26_fu_1414_p1.read();
}

void hard_tanh::thread_ap_return_27() {
    ap_return_27 = sext_ln1494_27_fu_1456_p1.read();
}

void hard_tanh::thread_ap_return_28() {
    ap_return_28 = sext_ln1494_28_fu_1498_p1.read();
}

void hard_tanh::thread_ap_return_29() {
    ap_return_29 = sext_ln1494_29_fu_1540_p1.read();
}

void hard_tanh::thread_ap_return_3() {
    ap_return_3 = sext_ln1494_3_fu_448_p1.read();
}

void hard_tanh::thread_ap_return_30() {
    ap_return_30 = sext_ln1494_30_fu_1582_p1.read();
}

void hard_tanh::thread_ap_return_31() {
    ap_return_31 = sext_ln331_fu_1624_p1.read();
}

void hard_tanh::thread_ap_return_4() {
    ap_return_4 = sext_ln1494_4_fu_490_p1.read();
}

void hard_tanh::thread_ap_return_5() {
    ap_return_5 = sext_ln1494_5_fu_532_p1.read();
}

void hard_tanh::thread_ap_return_6() {
    ap_return_6 = sext_ln1494_6_fu_574_p1.read();
}

void hard_tanh::thread_ap_return_7() {
    ap_return_7 = sext_ln1494_7_fu_616_p1.read();
}

void hard_tanh::thread_ap_return_8() {
    ap_return_8 = sext_ln1494_8_fu_658_p1.read();
}

void hard_tanh::thread_ap_return_9() {
    ap_return_9 = sext_ln1494_9_fu_700_p1.read();
}

void hard_tanh::thread_icmp_ln1494_10_fu_704_p2() {
    icmp_ln1494_10_fu_704_p2 = (!data_10_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_10_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_11_fu_746_p2() {
    icmp_ln1494_11_fu_746_p2 = (!data_11_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_11_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_12_fu_788_p2() {
    icmp_ln1494_12_fu_788_p2 = (!data_12_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_12_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_13_fu_830_p2() {
    icmp_ln1494_13_fu_830_p2 = (!data_13_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_13_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_14_fu_872_p2() {
    icmp_ln1494_14_fu_872_p2 = (!data_14_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_14_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_15_fu_914_p2() {
    icmp_ln1494_15_fu_914_p2 = (!data_15_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_15_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_16_fu_956_p2() {
    icmp_ln1494_16_fu_956_p2 = (!data_16_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_16_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_17_fu_998_p2() {
    icmp_ln1494_17_fu_998_p2 = (!data_17_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_17_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_18_fu_1040_p2() {
    icmp_ln1494_18_fu_1040_p2 = (!data_18_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_18_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_19_fu_1082_p2() {
    icmp_ln1494_19_fu_1082_p2 = (!data_19_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_19_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_1_fu_326_p2() {
    icmp_ln1494_1_fu_326_p2 = (!data_1_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_1_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_20_fu_1124_p2() {
    icmp_ln1494_20_fu_1124_p2 = (!data_20_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_20_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_21_fu_1166_p2() {
    icmp_ln1494_21_fu_1166_p2 = (!data_21_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_21_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_22_fu_1208_p2() {
    icmp_ln1494_22_fu_1208_p2 = (!data_22_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_22_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_23_fu_1250_p2() {
    icmp_ln1494_23_fu_1250_p2 = (!data_23_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_23_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_24_fu_1292_p2() {
    icmp_ln1494_24_fu_1292_p2 = (!data_24_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_24_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_25_fu_1334_p2() {
    icmp_ln1494_25_fu_1334_p2 = (!data_25_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_25_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_26_fu_1376_p2() {
    icmp_ln1494_26_fu_1376_p2 = (!data_26_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_26_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_27_fu_1418_p2() {
    icmp_ln1494_27_fu_1418_p2 = (!data_27_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_27_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_28_fu_1460_p2() {
    icmp_ln1494_28_fu_1460_p2 = (!data_28_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_28_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_29_fu_1502_p2() {
    icmp_ln1494_29_fu_1502_p2 = (!data_29_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_29_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_2_fu_368_p2() {
    icmp_ln1494_2_fu_368_p2 = (!data_2_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_2_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_30_fu_1544_p2() {
    icmp_ln1494_30_fu_1544_p2 = (!data_30_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_30_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_31_fu_1586_p2() {
    icmp_ln1494_31_fu_1586_p2 = (!data_31_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_31_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_3_fu_410_p2() {
    icmp_ln1494_3_fu_410_p2 = (!data_3_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_3_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_4_fu_452_p2() {
    icmp_ln1494_4_fu_452_p2 = (!data_4_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_4_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_5_fu_494_p2() {
    icmp_ln1494_5_fu_494_p2 = (!data_5_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_5_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_6_fu_536_p2() {
    icmp_ln1494_6_fu_536_p2 = (!data_6_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_6_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_7_fu_578_p2() {
    icmp_ln1494_7_fu_578_p2 = (!data_7_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_7_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_8_fu_620_p2() {
    icmp_ln1494_8_fu_620_p2 = (!data_8_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_8_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_9_fu_662_p2() {
    icmp_ln1494_9_fu_662_p2 = (!data_9_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_9_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1494_fu_284_p2() {
    icmp_ln1494_fu_284_p2 = (!data_0_V_read.read().is_01() || !ap_const_lv16_400.is_01())? sc_lv<1>(): (sc_bigint<16>(data_0_V_read.read()) > sc_bigint<16>(ap_const_lv16_400));
}

void hard_tanh::thread_icmp_ln1495_10_fu_710_p2() {
    icmp_ln1495_10_fu_710_p2 = (!data_10_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_10_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_11_fu_752_p2() {
    icmp_ln1495_11_fu_752_p2 = (!data_11_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_11_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_12_fu_794_p2() {
    icmp_ln1495_12_fu_794_p2 = (!data_12_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_12_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_13_fu_836_p2() {
    icmp_ln1495_13_fu_836_p2 = (!data_13_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_13_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_14_fu_878_p2() {
    icmp_ln1495_14_fu_878_p2 = (!data_14_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_14_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_15_fu_920_p2() {
    icmp_ln1495_15_fu_920_p2 = (!data_15_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_15_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_16_fu_962_p2() {
    icmp_ln1495_16_fu_962_p2 = (!data_16_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_16_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_17_fu_1004_p2() {
    icmp_ln1495_17_fu_1004_p2 = (!data_17_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_17_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_18_fu_1046_p2() {
    icmp_ln1495_18_fu_1046_p2 = (!data_18_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_18_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_19_fu_1088_p2() {
    icmp_ln1495_19_fu_1088_p2 = (!data_19_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_19_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_1_fu_332_p2() {
    icmp_ln1495_1_fu_332_p2 = (!data_1_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_1_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_20_fu_1130_p2() {
    icmp_ln1495_20_fu_1130_p2 = (!data_20_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_20_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_21_fu_1172_p2() {
    icmp_ln1495_21_fu_1172_p2 = (!data_21_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_21_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_22_fu_1214_p2() {
    icmp_ln1495_22_fu_1214_p2 = (!data_22_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_22_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_23_fu_1256_p2() {
    icmp_ln1495_23_fu_1256_p2 = (!data_23_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_23_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_24_fu_1298_p2() {
    icmp_ln1495_24_fu_1298_p2 = (!data_24_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_24_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_25_fu_1340_p2() {
    icmp_ln1495_25_fu_1340_p2 = (!data_25_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_25_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_26_fu_1382_p2() {
    icmp_ln1495_26_fu_1382_p2 = (!data_26_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_26_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_27_fu_1424_p2() {
    icmp_ln1495_27_fu_1424_p2 = (!data_27_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_27_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_28_fu_1466_p2() {
    icmp_ln1495_28_fu_1466_p2 = (!data_28_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_28_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_29_fu_1508_p2() {
    icmp_ln1495_29_fu_1508_p2 = (!data_29_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_29_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_2_fu_374_p2() {
    icmp_ln1495_2_fu_374_p2 = (!data_2_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_2_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_30_fu_1550_p2() {
    icmp_ln1495_30_fu_1550_p2 = (!data_30_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_30_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_31_fu_1592_p2() {
    icmp_ln1495_31_fu_1592_p2 = (!data_31_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_31_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_3_fu_416_p2() {
    icmp_ln1495_3_fu_416_p2 = (!data_3_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_3_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_4_fu_458_p2() {
    icmp_ln1495_4_fu_458_p2 = (!data_4_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_4_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_5_fu_500_p2() {
    icmp_ln1495_5_fu_500_p2 = (!data_5_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_5_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_6_fu_542_p2() {
    icmp_ln1495_6_fu_542_p2 = (!data_6_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_6_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_7_fu_584_p2() {
    icmp_ln1495_7_fu_584_p2 = (!data_7_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_7_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_8_fu_626_p2() {
    icmp_ln1495_8_fu_626_p2 = (!data_8_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_8_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_9_fu_668_p2() {
    icmp_ln1495_9_fu_668_p2 = (!data_9_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_9_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_icmp_ln1495_fu_290_p2() {
    icmp_ln1495_fu_290_p2 = (!data_0_V_read.read().is_01() || !ap_const_lv16_FC00.is_01())? sc_lv<1>(): (sc_bigint<16>(data_0_V_read.read()) < sc_bigint<16>(ap_const_lv16_FC00));
}

void hard_tanh::thread_or_ln1494_10_fu_728_p2() {
    or_ln1494_10_fu_728_p2 = (icmp_ln1494_10_fu_704_p2.read() | icmp_ln1495_10_fu_710_p2.read());
}

void hard_tanh::thread_or_ln1494_11_fu_770_p2() {
    or_ln1494_11_fu_770_p2 = (icmp_ln1494_11_fu_746_p2.read() | icmp_ln1495_11_fu_752_p2.read());
}

void hard_tanh::thread_or_ln1494_12_fu_812_p2() {
    or_ln1494_12_fu_812_p2 = (icmp_ln1494_12_fu_788_p2.read() | icmp_ln1495_12_fu_794_p2.read());
}

void hard_tanh::thread_or_ln1494_13_fu_854_p2() {
    or_ln1494_13_fu_854_p2 = (icmp_ln1494_13_fu_830_p2.read() | icmp_ln1495_13_fu_836_p2.read());
}

void hard_tanh::thread_or_ln1494_14_fu_896_p2() {
    or_ln1494_14_fu_896_p2 = (icmp_ln1494_14_fu_872_p2.read() | icmp_ln1495_14_fu_878_p2.read());
}

void hard_tanh::thread_or_ln1494_15_fu_938_p2() {
    or_ln1494_15_fu_938_p2 = (icmp_ln1494_15_fu_914_p2.read() | icmp_ln1495_15_fu_920_p2.read());
}

void hard_tanh::thread_or_ln1494_16_fu_980_p2() {
    or_ln1494_16_fu_980_p2 = (icmp_ln1494_16_fu_956_p2.read() | icmp_ln1495_16_fu_962_p2.read());
}

void hard_tanh::thread_or_ln1494_17_fu_1022_p2() {
    or_ln1494_17_fu_1022_p2 = (icmp_ln1494_17_fu_998_p2.read() | icmp_ln1495_17_fu_1004_p2.read());
}

void hard_tanh::thread_or_ln1494_18_fu_1064_p2() {
    or_ln1494_18_fu_1064_p2 = (icmp_ln1494_18_fu_1040_p2.read() | icmp_ln1495_18_fu_1046_p2.read());
}

void hard_tanh::thread_or_ln1494_19_fu_1106_p2() {
    or_ln1494_19_fu_1106_p2 = (icmp_ln1494_19_fu_1082_p2.read() | icmp_ln1495_19_fu_1088_p2.read());
}

void hard_tanh::thread_or_ln1494_1_fu_350_p2() {
    or_ln1494_1_fu_350_p2 = (icmp_ln1494_1_fu_326_p2.read() | icmp_ln1495_1_fu_332_p2.read());
}

void hard_tanh::thread_or_ln1494_20_fu_1148_p2() {
    or_ln1494_20_fu_1148_p2 = (icmp_ln1494_20_fu_1124_p2.read() | icmp_ln1495_20_fu_1130_p2.read());
}

void hard_tanh::thread_or_ln1494_21_fu_1190_p2() {
    or_ln1494_21_fu_1190_p2 = (icmp_ln1494_21_fu_1166_p2.read() | icmp_ln1495_21_fu_1172_p2.read());
}

void hard_tanh::thread_or_ln1494_22_fu_1232_p2() {
    or_ln1494_22_fu_1232_p2 = (icmp_ln1494_22_fu_1208_p2.read() | icmp_ln1495_22_fu_1214_p2.read());
}

void hard_tanh::thread_or_ln1494_23_fu_1274_p2() {
    or_ln1494_23_fu_1274_p2 = (icmp_ln1494_23_fu_1250_p2.read() | icmp_ln1495_23_fu_1256_p2.read());
}

void hard_tanh::thread_or_ln1494_24_fu_1316_p2() {
    or_ln1494_24_fu_1316_p2 = (icmp_ln1494_24_fu_1292_p2.read() | icmp_ln1495_24_fu_1298_p2.read());
}

void hard_tanh::thread_or_ln1494_25_fu_1358_p2() {
    or_ln1494_25_fu_1358_p2 = (icmp_ln1494_25_fu_1334_p2.read() | icmp_ln1495_25_fu_1340_p2.read());
}

void hard_tanh::thread_or_ln1494_26_fu_1400_p2() {
    or_ln1494_26_fu_1400_p2 = (icmp_ln1494_26_fu_1376_p2.read() | icmp_ln1495_26_fu_1382_p2.read());
}

void hard_tanh::thread_or_ln1494_27_fu_1442_p2() {
    or_ln1494_27_fu_1442_p2 = (icmp_ln1494_27_fu_1418_p2.read() | icmp_ln1495_27_fu_1424_p2.read());
}

void hard_tanh::thread_or_ln1494_28_fu_1484_p2() {
    or_ln1494_28_fu_1484_p2 = (icmp_ln1494_28_fu_1460_p2.read() | icmp_ln1495_28_fu_1466_p2.read());
}

void hard_tanh::thread_or_ln1494_29_fu_1526_p2() {
    or_ln1494_29_fu_1526_p2 = (icmp_ln1494_29_fu_1502_p2.read() | icmp_ln1495_29_fu_1508_p2.read());
}

void hard_tanh::thread_or_ln1494_2_fu_392_p2() {
    or_ln1494_2_fu_392_p2 = (icmp_ln1494_2_fu_368_p2.read() | icmp_ln1495_2_fu_374_p2.read());
}

void hard_tanh::thread_or_ln1494_30_fu_1568_p2() {
    or_ln1494_30_fu_1568_p2 = (icmp_ln1494_30_fu_1544_p2.read() | icmp_ln1495_30_fu_1550_p2.read());
}

void hard_tanh::thread_or_ln1494_31_fu_1610_p2() {
    or_ln1494_31_fu_1610_p2 = (icmp_ln1494_31_fu_1586_p2.read() | icmp_ln1495_31_fu_1592_p2.read());
}

void hard_tanh::thread_or_ln1494_3_fu_434_p2() {
    or_ln1494_3_fu_434_p2 = (icmp_ln1494_3_fu_410_p2.read() | icmp_ln1495_3_fu_416_p2.read());
}

void hard_tanh::thread_or_ln1494_4_fu_476_p2() {
    or_ln1494_4_fu_476_p2 = (icmp_ln1494_4_fu_452_p2.read() | icmp_ln1495_4_fu_458_p2.read());
}

void hard_tanh::thread_or_ln1494_5_fu_518_p2() {
    or_ln1494_5_fu_518_p2 = (icmp_ln1494_5_fu_494_p2.read() | icmp_ln1495_5_fu_500_p2.read());
}

void hard_tanh::thread_or_ln1494_6_fu_560_p2() {
    or_ln1494_6_fu_560_p2 = (icmp_ln1494_6_fu_536_p2.read() | icmp_ln1495_6_fu_542_p2.read());
}

void hard_tanh::thread_or_ln1494_7_fu_602_p2() {
    or_ln1494_7_fu_602_p2 = (icmp_ln1494_7_fu_578_p2.read() | icmp_ln1495_7_fu_584_p2.read());
}

void hard_tanh::thread_or_ln1494_8_fu_644_p2() {
    or_ln1494_8_fu_644_p2 = (icmp_ln1494_8_fu_620_p2.read() | icmp_ln1495_8_fu_626_p2.read());
}

void hard_tanh::thread_or_ln1494_9_fu_686_p2() {
    or_ln1494_9_fu_686_p2 = (icmp_ln1494_9_fu_662_p2.read() | icmp_ln1495_9_fu_668_p2.read());
}

void hard_tanh::thread_or_ln1494_fu_308_p2() {
    or_ln1494_fu_308_p2 = (icmp_ln1494_fu_284_p2.read() | icmp_ln1495_fu_290_p2.read());
}

void hard_tanh::thread_select_ln1494_10_fu_510_p3() {
    select_ln1494_10_fu_510_p3 = (!icmp_ln1494_5_fu_494_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_5_fu_494_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_12_fu_552_p3() {
    select_ln1494_12_fu_552_p3 = (!icmp_ln1494_6_fu_536_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_6_fu_536_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_14_fu_594_p3() {
    select_ln1494_14_fu_594_p3 = (!icmp_ln1494_7_fu_578_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_7_fu_578_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_16_fu_636_p3() {
    select_ln1494_16_fu_636_p3 = (!icmp_ln1494_8_fu_620_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_8_fu_620_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_18_fu_678_p3() {
    select_ln1494_18_fu_678_p3 = (!icmp_ln1494_9_fu_662_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_9_fu_662_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_20_fu_720_p3() {
    select_ln1494_20_fu_720_p3 = (!icmp_ln1494_10_fu_704_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_10_fu_704_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_22_fu_762_p3() {
    select_ln1494_22_fu_762_p3 = (!icmp_ln1494_11_fu_746_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_11_fu_746_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_24_fu_804_p3() {
    select_ln1494_24_fu_804_p3 = (!icmp_ln1494_12_fu_788_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_12_fu_788_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_26_fu_846_p3() {
    select_ln1494_26_fu_846_p3 = (!icmp_ln1494_13_fu_830_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_13_fu_830_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_28_fu_888_p3() {
    select_ln1494_28_fu_888_p3 = (!icmp_ln1494_14_fu_872_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_14_fu_872_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_2_fu_342_p3() {
    select_ln1494_2_fu_342_p3 = (!icmp_ln1494_1_fu_326_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_1_fu_326_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_30_fu_930_p3() {
    select_ln1494_30_fu_930_p3 = (!icmp_ln1494_15_fu_914_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_15_fu_914_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_32_fu_972_p3() {
    select_ln1494_32_fu_972_p3 = (!icmp_ln1494_16_fu_956_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_16_fu_956_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_34_fu_1014_p3() {
    select_ln1494_34_fu_1014_p3 = (!icmp_ln1494_17_fu_998_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_17_fu_998_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_36_fu_1056_p3() {
    select_ln1494_36_fu_1056_p3 = (!icmp_ln1494_18_fu_1040_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_18_fu_1040_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_38_fu_1098_p3() {
    select_ln1494_38_fu_1098_p3 = (!icmp_ln1494_19_fu_1082_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_19_fu_1082_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_40_fu_1140_p3() {
    select_ln1494_40_fu_1140_p3 = (!icmp_ln1494_20_fu_1124_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_20_fu_1124_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_42_fu_1182_p3() {
    select_ln1494_42_fu_1182_p3 = (!icmp_ln1494_21_fu_1166_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_21_fu_1166_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_44_fu_1224_p3() {
    select_ln1494_44_fu_1224_p3 = (!icmp_ln1494_22_fu_1208_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_22_fu_1208_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_46_fu_1266_p3() {
    select_ln1494_46_fu_1266_p3 = (!icmp_ln1494_23_fu_1250_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_23_fu_1250_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_48_fu_1308_p3() {
    select_ln1494_48_fu_1308_p3 = (!icmp_ln1494_24_fu_1292_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_24_fu_1292_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_4_fu_384_p3() {
    select_ln1494_4_fu_384_p3 = (!icmp_ln1494_2_fu_368_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_2_fu_368_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_50_fu_1350_p3() {
    select_ln1494_50_fu_1350_p3 = (!icmp_ln1494_25_fu_1334_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_25_fu_1334_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_52_fu_1392_p3() {
    select_ln1494_52_fu_1392_p3 = (!icmp_ln1494_26_fu_1376_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_26_fu_1376_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_54_fu_1434_p3() {
    select_ln1494_54_fu_1434_p3 = (!icmp_ln1494_27_fu_1418_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_27_fu_1418_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_56_fu_1476_p3() {
    select_ln1494_56_fu_1476_p3 = (!icmp_ln1494_28_fu_1460_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_28_fu_1460_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_58_fu_1518_p3() {
    select_ln1494_58_fu_1518_p3 = (!icmp_ln1494_29_fu_1502_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_29_fu_1502_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_60_fu_1560_p3() {
    select_ln1494_60_fu_1560_p3 = (!icmp_ln1494_30_fu_1544_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_30_fu_1544_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_62_fu_1602_p3() {
    select_ln1494_62_fu_1602_p3 = (!icmp_ln1494_31_fu_1586_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_31_fu_1586_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_64_fu_314_p3() {
    select_ln1494_64_fu_314_p3 = (!or_ln1494_fu_308_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_fu_308_p2.read()[0].to_bool())? select_ln1494_fu_300_p3.read(): trunc_ln347_fu_296_p1.read());
}

void hard_tanh::thread_select_ln1494_65_fu_356_p3() {
    select_ln1494_65_fu_356_p3 = (!or_ln1494_1_fu_350_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_1_fu_350_p2.read()[0].to_bool())? select_ln1494_2_fu_342_p3.read(): trunc_ln347_32_fu_338_p1.read());
}

void hard_tanh::thread_select_ln1494_66_fu_398_p3() {
    select_ln1494_66_fu_398_p3 = (!or_ln1494_2_fu_392_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_2_fu_392_p2.read()[0].to_bool())? select_ln1494_4_fu_384_p3.read(): trunc_ln347_33_fu_380_p1.read());
}

void hard_tanh::thread_select_ln1494_67_fu_440_p3() {
    select_ln1494_67_fu_440_p3 = (!or_ln1494_3_fu_434_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_3_fu_434_p2.read()[0].to_bool())? select_ln1494_6_fu_426_p3.read(): trunc_ln347_34_fu_422_p1.read());
}

void hard_tanh::thread_select_ln1494_68_fu_482_p3() {
    select_ln1494_68_fu_482_p3 = (!or_ln1494_4_fu_476_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_4_fu_476_p2.read()[0].to_bool())? select_ln1494_8_fu_468_p3.read(): trunc_ln347_35_fu_464_p1.read());
}

void hard_tanh::thread_select_ln1494_69_fu_524_p3() {
    select_ln1494_69_fu_524_p3 = (!or_ln1494_5_fu_518_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_5_fu_518_p2.read()[0].to_bool())? select_ln1494_10_fu_510_p3.read(): trunc_ln347_36_fu_506_p1.read());
}

void hard_tanh::thread_select_ln1494_6_fu_426_p3() {
    select_ln1494_6_fu_426_p3 = (!icmp_ln1494_3_fu_410_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_3_fu_410_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_70_fu_566_p3() {
    select_ln1494_70_fu_566_p3 = (!or_ln1494_6_fu_560_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_6_fu_560_p2.read()[0].to_bool())? select_ln1494_12_fu_552_p3.read(): trunc_ln347_37_fu_548_p1.read());
}

void hard_tanh::thread_select_ln1494_71_fu_608_p3() {
    select_ln1494_71_fu_608_p3 = (!or_ln1494_7_fu_602_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_7_fu_602_p2.read()[0].to_bool())? select_ln1494_14_fu_594_p3.read(): trunc_ln347_38_fu_590_p1.read());
}

void hard_tanh::thread_select_ln1494_72_fu_650_p3() {
    select_ln1494_72_fu_650_p3 = (!or_ln1494_8_fu_644_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_8_fu_644_p2.read()[0].to_bool())? select_ln1494_16_fu_636_p3.read(): trunc_ln347_39_fu_632_p1.read());
}

void hard_tanh::thread_select_ln1494_73_fu_692_p3() {
    select_ln1494_73_fu_692_p3 = (!or_ln1494_9_fu_686_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_9_fu_686_p2.read()[0].to_bool())? select_ln1494_18_fu_678_p3.read(): trunc_ln347_40_fu_674_p1.read());
}

void hard_tanh::thread_select_ln1494_74_fu_734_p3() {
    select_ln1494_74_fu_734_p3 = (!or_ln1494_10_fu_728_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_10_fu_728_p2.read()[0].to_bool())? select_ln1494_20_fu_720_p3.read(): trunc_ln347_41_fu_716_p1.read());
}

void hard_tanh::thread_select_ln1494_75_fu_776_p3() {
    select_ln1494_75_fu_776_p3 = (!or_ln1494_11_fu_770_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_11_fu_770_p2.read()[0].to_bool())? select_ln1494_22_fu_762_p3.read(): trunc_ln347_42_fu_758_p1.read());
}

void hard_tanh::thread_select_ln1494_76_fu_818_p3() {
    select_ln1494_76_fu_818_p3 = (!or_ln1494_12_fu_812_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_12_fu_812_p2.read()[0].to_bool())? select_ln1494_24_fu_804_p3.read(): trunc_ln347_43_fu_800_p1.read());
}

void hard_tanh::thread_select_ln1494_77_fu_860_p3() {
    select_ln1494_77_fu_860_p3 = (!or_ln1494_13_fu_854_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_13_fu_854_p2.read()[0].to_bool())? select_ln1494_26_fu_846_p3.read(): trunc_ln347_44_fu_842_p1.read());
}

void hard_tanh::thread_select_ln1494_78_fu_902_p3() {
    select_ln1494_78_fu_902_p3 = (!or_ln1494_14_fu_896_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_14_fu_896_p2.read()[0].to_bool())? select_ln1494_28_fu_888_p3.read(): trunc_ln347_45_fu_884_p1.read());
}

void hard_tanh::thread_select_ln1494_79_fu_944_p3() {
    select_ln1494_79_fu_944_p3 = (!or_ln1494_15_fu_938_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_15_fu_938_p2.read()[0].to_bool())? select_ln1494_30_fu_930_p3.read(): trunc_ln347_46_fu_926_p1.read());
}

void hard_tanh::thread_select_ln1494_80_fu_986_p3() {
    select_ln1494_80_fu_986_p3 = (!or_ln1494_16_fu_980_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_16_fu_980_p2.read()[0].to_bool())? select_ln1494_32_fu_972_p3.read(): trunc_ln347_47_fu_968_p1.read());
}

void hard_tanh::thread_select_ln1494_81_fu_1028_p3() {
    select_ln1494_81_fu_1028_p3 = (!or_ln1494_17_fu_1022_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_17_fu_1022_p2.read()[0].to_bool())? select_ln1494_34_fu_1014_p3.read(): trunc_ln347_48_fu_1010_p1.read());
}

void hard_tanh::thread_select_ln1494_82_fu_1070_p3() {
    select_ln1494_82_fu_1070_p3 = (!or_ln1494_18_fu_1064_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_18_fu_1064_p2.read()[0].to_bool())? select_ln1494_36_fu_1056_p3.read(): trunc_ln347_49_fu_1052_p1.read());
}

void hard_tanh::thread_select_ln1494_83_fu_1112_p3() {
    select_ln1494_83_fu_1112_p3 = (!or_ln1494_19_fu_1106_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_19_fu_1106_p2.read()[0].to_bool())? select_ln1494_38_fu_1098_p3.read(): trunc_ln347_50_fu_1094_p1.read());
}

void hard_tanh::thread_select_ln1494_84_fu_1154_p3() {
    select_ln1494_84_fu_1154_p3 = (!or_ln1494_20_fu_1148_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_20_fu_1148_p2.read()[0].to_bool())? select_ln1494_40_fu_1140_p3.read(): trunc_ln347_51_fu_1136_p1.read());
}

void hard_tanh::thread_select_ln1494_85_fu_1196_p3() {
    select_ln1494_85_fu_1196_p3 = (!or_ln1494_21_fu_1190_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_21_fu_1190_p2.read()[0].to_bool())? select_ln1494_42_fu_1182_p3.read(): trunc_ln347_52_fu_1178_p1.read());
}

void hard_tanh::thread_select_ln1494_86_fu_1238_p3() {
    select_ln1494_86_fu_1238_p3 = (!or_ln1494_22_fu_1232_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_22_fu_1232_p2.read()[0].to_bool())? select_ln1494_44_fu_1224_p3.read(): trunc_ln347_53_fu_1220_p1.read());
}

void hard_tanh::thread_select_ln1494_87_fu_1280_p3() {
    select_ln1494_87_fu_1280_p3 = (!or_ln1494_23_fu_1274_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_23_fu_1274_p2.read()[0].to_bool())? select_ln1494_46_fu_1266_p3.read(): trunc_ln347_54_fu_1262_p1.read());
}

void hard_tanh::thread_select_ln1494_88_fu_1322_p3() {
    select_ln1494_88_fu_1322_p3 = (!or_ln1494_24_fu_1316_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_24_fu_1316_p2.read()[0].to_bool())? select_ln1494_48_fu_1308_p3.read(): trunc_ln347_55_fu_1304_p1.read());
}

void hard_tanh::thread_select_ln1494_89_fu_1364_p3() {
    select_ln1494_89_fu_1364_p3 = (!or_ln1494_25_fu_1358_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_25_fu_1358_p2.read()[0].to_bool())? select_ln1494_50_fu_1350_p3.read(): trunc_ln347_56_fu_1346_p1.read());
}

void hard_tanh::thread_select_ln1494_8_fu_468_p3() {
    select_ln1494_8_fu_468_p3 = (!icmp_ln1494_4_fu_452_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_4_fu_452_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_select_ln1494_90_fu_1406_p3() {
    select_ln1494_90_fu_1406_p3 = (!or_ln1494_26_fu_1400_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_26_fu_1400_p2.read()[0].to_bool())? select_ln1494_52_fu_1392_p3.read(): trunc_ln347_57_fu_1388_p1.read());
}

void hard_tanh::thread_select_ln1494_91_fu_1448_p3() {
    select_ln1494_91_fu_1448_p3 = (!or_ln1494_27_fu_1442_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_27_fu_1442_p2.read()[0].to_bool())? select_ln1494_54_fu_1434_p3.read(): trunc_ln347_58_fu_1430_p1.read());
}

void hard_tanh::thread_select_ln1494_92_fu_1490_p3() {
    select_ln1494_92_fu_1490_p3 = (!or_ln1494_28_fu_1484_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_28_fu_1484_p2.read()[0].to_bool())? select_ln1494_56_fu_1476_p3.read(): trunc_ln347_59_fu_1472_p1.read());
}

void hard_tanh::thread_select_ln1494_93_fu_1532_p3() {
    select_ln1494_93_fu_1532_p3 = (!or_ln1494_29_fu_1526_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_29_fu_1526_p2.read()[0].to_bool())? select_ln1494_58_fu_1518_p3.read(): trunc_ln347_60_fu_1514_p1.read());
}

void hard_tanh::thread_select_ln1494_94_fu_1574_p3() {
    select_ln1494_94_fu_1574_p3 = (!or_ln1494_30_fu_1568_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_30_fu_1568_p2.read()[0].to_bool())? select_ln1494_60_fu_1560_p3.read(): trunc_ln347_61_fu_1556_p1.read());
}

void hard_tanh::thread_select_ln1494_95_fu_1616_p3() {
    select_ln1494_95_fu_1616_p3 = (!or_ln1494_31_fu_1610_p2.read()[0].is_01())? sc_lv<12>(): ((or_ln1494_31_fu_1610_p2.read()[0].to_bool())? select_ln1494_62_fu_1602_p3.read(): trunc_ln347_62_fu_1598_p1.read());
}

void hard_tanh::thread_select_ln1494_fu_300_p3() {
    select_ln1494_fu_300_p3 = (!icmp_ln1494_fu_284_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln1494_fu_284_p2.read()[0].to_bool())? ap_const_lv12_400: ap_const_lv12_C00);
}

void hard_tanh::thread_sext_ln1494_10_fu_742_p1() {
    sext_ln1494_10_fu_742_p1 = esl_sext<16,12>(select_ln1494_74_fu_734_p3.read());
}

void hard_tanh::thread_sext_ln1494_11_fu_784_p1() {
    sext_ln1494_11_fu_784_p1 = esl_sext<16,12>(select_ln1494_75_fu_776_p3.read());
}

void hard_tanh::thread_sext_ln1494_12_fu_826_p1() {
    sext_ln1494_12_fu_826_p1 = esl_sext<16,12>(select_ln1494_76_fu_818_p3.read());
}

void hard_tanh::thread_sext_ln1494_13_fu_868_p1() {
    sext_ln1494_13_fu_868_p1 = esl_sext<16,12>(select_ln1494_77_fu_860_p3.read());
}

void hard_tanh::thread_sext_ln1494_14_fu_910_p1() {
    sext_ln1494_14_fu_910_p1 = esl_sext<16,12>(select_ln1494_78_fu_902_p3.read());
}

void hard_tanh::thread_sext_ln1494_15_fu_952_p1() {
    sext_ln1494_15_fu_952_p1 = esl_sext<16,12>(select_ln1494_79_fu_944_p3.read());
}

void hard_tanh::thread_sext_ln1494_16_fu_994_p1() {
    sext_ln1494_16_fu_994_p1 = esl_sext<16,12>(select_ln1494_80_fu_986_p3.read());
}

void hard_tanh::thread_sext_ln1494_17_fu_1036_p1() {
    sext_ln1494_17_fu_1036_p1 = esl_sext<16,12>(select_ln1494_81_fu_1028_p3.read());
}

void hard_tanh::thread_sext_ln1494_18_fu_1078_p1() {
    sext_ln1494_18_fu_1078_p1 = esl_sext<16,12>(select_ln1494_82_fu_1070_p3.read());
}

void hard_tanh::thread_sext_ln1494_19_fu_1120_p1() {
    sext_ln1494_19_fu_1120_p1 = esl_sext<16,12>(select_ln1494_83_fu_1112_p3.read());
}

void hard_tanh::thread_sext_ln1494_1_fu_364_p1() {
    sext_ln1494_1_fu_364_p1 = esl_sext<16,12>(select_ln1494_65_fu_356_p3.read());
}

void hard_tanh::thread_sext_ln1494_20_fu_1162_p1() {
    sext_ln1494_20_fu_1162_p1 = esl_sext<16,12>(select_ln1494_84_fu_1154_p3.read());
}

void hard_tanh::thread_sext_ln1494_21_fu_1204_p1() {
    sext_ln1494_21_fu_1204_p1 = esl_sext<16,12>(select_ln1494_85_fu_1196_p3.read());
}

void hard_tanh::thread_sext_ln1494_22_fu_1246_p1() {
    sext_ln1494_22_fu_1246_p1 = esl_sext<16,12>(select_ln1494_86_fu_1238_p3.read());
}

void hard_tanh::thread_sext_ln1494_23_fu_1288_p1() {
    sext_ln1494_23_fu_1288_p1 = esl_sext<16,12>(select_ln1494_87_fu_1280_p3.read());
}

void hard_tanh::thread_sext_ln1494_24_fu_1330_p1() {
    sext_ln1494_24_fu_1330_p1 = esl_sext<16,12>(select_ln1494_88_fu_1322_p3.read());
}

void hard_tanh::thread_sext_ln1494_25_fu_1372_p1() {
    sext_ln1494_25_fu_1372_p1 = esl_sext<16,12>(select_ln1494_89_fu_1364_p3.read());
}

void hard_tanh::thread_sext_ln1494_26_fu_1414_p1() {
    sext_ln1494_26_fu_1414_p1 = esl_sext<16,12>(select_ln1494_90_fu_1406_p3.read());
}

void hard_tanh::thread_sext_ln1494_27_fu_1456_p1() {
    sext_ln1494_27_fu_1456_p1 = esl_sext<16,12>(select_ln1494_91_fu_1448_p3.read());
}

void hard_tanh::thread_sext_ln1494_28_fu_1498_p1() {
    sext_ln1494_28_fu_1498_p1 = esl_sext<16,12>(select_ln1494_92_fu_1490_p3.read());
}

void hard_tanh::thread_sext_ln1494_29_fu_1540_p1() {
    sext_ln1494_29_fu_1540_p1 = esl_sext<16,12>(select_ln1494_93_fu_1532_p3.read());
}

void hard_tanh::thread_sext_ln1494_2_fu_406_p1() {
    sext_ln1494_2_fu_406_p1 = esl_sext<16,12>(select_ln1494_66_fu_398_p3.read());
}

void hard_tanh::thread_sext_ln1494_30_fu_1582_p1() {
    sext_ln1494_30_fu_1582_p1 = esl_sext<16,12>(select_ln1494_94_fu_1574_p3.read());
}

void hard_tanh::thread_sext_ln1494_3_fu_448_p1() {
    sext_ln1494_3_fu_448_p1 = esl_sext<16,12>(select_ln1494_67_fu_440_p3.read());
}

void hard_tanh::thread_sext_ln1494_4_fu_490_p1() {
    sext_ln1494_4_fu_490_p1 = esl_sext<16,12>(select_ln1494_68_fu_482_p3.read());
}

void hard_tanh::thread_sext_ln1494_5_fu_532_p1() {
    sext_ln1494_5_fu_532_p1 = esl_sext<16,12>(select_ln1494_69_fu_524_p3.read());
}

void hard_tanh::thread_sext_ln1494_6_fu_574_p1() {
    sext_ln1494_6_fu_574_p1 = esl_sext<16,12>(select_ln1494_70_fu_566_p3.read());
}

void hard_tanh::thread_sext_ln1494_7_fu_616_p1() {
    sext_ln1494_7_fu_616_p1 = esl_sext<16,12>(select_ln1494_71_fu_608_p3.read());
}

void hard_tanh::thread_sext_ln1494_8_fu_658_p1() {
    sext_ln1494_8_fu_658_p1 = esl_sext<16,12>(select_ln1494_72_fu_650_p3.read());
}

void hard_tanh::thread_sext_ln1494_9_fu_700_p1() {
    sext_ln1494_9_fu_700_p1 = esl_sext<16,12>(select_ln1494_73_fu_692_p3.read());
}

void hard_tanh::thread_sext_ln1494_fu_322_p1() {
    sext_ln1494_fu_322_p1 = esl_sext<16,12>(select_ln1494_64_fu_314_p3.read());
}

void hard_tanh::thread_sext_ln331_fu_1624_p1() {
    sext_ln331_fu_1624_p1 = esl_sext<16,12>(select_ln1494_95_fu_1616_p3.read());
}

void hard_tanh::thread_trunc_ln347_32_fu_338_p1() {
    trunc_ln347_32_fu_338_p1 = data_1_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_33_fu_380_p1() {
    trunc_ln347_33_fu_380_p1 = data_2_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_34_fu_422_p1() {
    trunc_ln347_34_fu_422_p1 = data_3_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_35_fu_464_p1() {
    trunc_ln347_35_fu_464_p1 = data_4_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_36_fu_506_p1() {
    trunc_ln347_36_fu_506_p1 = data_5_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_37_fu_548_p1() {
    trunc_ln347_37_fu_548_p1 = data_6_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_38_fu_590_p1() {
    trunc_ln347_38_fu_590_p1 = data_7_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_39_fu_632_p1() {
    trunc_ln347_39_fu_632_p1 = data_8_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_40_fu_674_p1() {
    trunc_ln347_40_fu_674_p1 = data_9_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_41_fu_716_p1() {
    trunc_ln347_41_fu_716_p1 = data_10_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_42_fu_758_p1() {
    trunc_ln347_42_fu_758_p1 = data_11_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_43_fu_800_p1() {
    trunc_ln347_43_fu_800_p1 = data_12_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_44_fu_842_p1() {
    trunc_ln347_44_fu_842_p1 = data_13_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_45_fu_884_p1() {
    trunc_ln347_45_fu_884_p1 = data_14_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_46_fu_926_p1() {
    trunc_ln347_46_fu_926_p1 = data_15_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_47_fu_968_p1() {
    trunc_ln347_47_fu_968_p1 = data_16_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_48_fu_1010_p1() {
    trunc_ln347_48_fu_1010_p1 = data_17_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_49_fu_1052_p1() {
    trunc_ln347_49_fu_1052_p1 = data_18_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_50_fu_1094_p1() {
    trunc_ln347_50_fu_1094_p1 = data_19_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_51_fu_1136_p1() {
    trunc_ln347_51_fu_1136_p1 = data_20_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_52_fu_1178_p1() {
    trunc_ln347_52_fu_1178_p1 = data_21_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_53_fu_1220_p1() {
    trunc_ln347_53_fu_1220_p1 = data_22_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_54_fu_1262_p1() {
    trunc_ln347_54_fu_1262_p1 = data_23_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_55_fu_1304_p1() {
    trunc_ln347_55_fu_1304_p1 = data_24_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_56_fu_1346_p1() {
    trunc_ln347_56_fu_1346_p1 = data_25_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_57_fu_1388_p1() {
    trunc_ln347_57_fu_1388_p1 = data_26_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_58_fu_1430_p1() {
    trunc_ln347_58_fu_1430_p1 = data_27_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_59_fu_1472_p1() {
    trunc_ln347_59_fu_1472_p1 = data_28_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_60_fu_1514_p1() {
    trunc_ln347_60_fu_1514_p1 = data_29_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_61_fu_1556_p1() {
    trunc_ln347_61_fu_1556_p1 = data_30_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_62_fu_1598_p1() {
    trunc_ln347_62_fu_1598_p1 = data_31_V_read.read().range(12-1, 0);
}

void hard_tanh::thread_trunc_ln347_fu_296_p1() {
    trunc_ln347_fu_296_p1 = data_0_V_read.read().range(12-1, 0);
}

}

