Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    input_1:
      Precision:
        result: ap_fixed<16,6>
    lstm:
      Precision: ap_fixed<16,6>
    lstm_tanh:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      table_size: 1024
      table_t: ap_fixed<18,8>
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
KerasModel: !keras_model 'my-hls-test/keras_model.h5'
OutputDir: my-hls-test
ProjectName: myproject
Stamp: F9179a77
XilinxPart: xcku115-flvb2104-2-i
