-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lstm_tail_02 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    gate_i_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_i_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_i_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_i_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_i_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_i_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_i_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_i_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_f_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_f_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_f_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_f_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_f_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_f_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_f_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_f_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_g_0_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    gate_g_1_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    gate_g_2_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    gate_g_3_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    gate_g_4_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    gate_g_5_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    gate_g_6_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    gate_g_7_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    gate_o_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_o_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_o_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_o_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_o_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_o_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_o_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    gate_o_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    c_pre_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    c_pre_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    c_pre_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    c_pre_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    c_pre_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    c_pre_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    c_pre_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    c_pre_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of lstm_tail_02 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";

    signal gate_o_7_V_read_2_reg_2497 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal gate_o_7_V_read_2_reg_2497_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_6_V_read31_reg_2502 : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_6_V_read31_reg_2502_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_5_V_read_2_reg_2507 : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_5_V_read_2_reg_2507_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_4_V_read_2_reg_2512 : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_4_V_read_2_reg_2512_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_3_V_read_2_reg_2517 : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_3_V_read_2_reg_2517_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_2_V_read_2_reg_2522 : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_2_V_read_2_reg_2522_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_1_V_read_2_reg_2527 : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_1_V_read_2_reg_2527_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_0_V_read_2_reg_2532 : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_0_V_read_2_reg_2532_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_reg_2537 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_1_reg_2542 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_2_reg_2547 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_3_reg_2552 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_4_reg_2557 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_5_reg_2562 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_6_reg_2567 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_7_reg_2572 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_8_reg_2577 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_9_reg_2582 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_10_reg_2587 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_11_reg_2592 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_12_reg_2597 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_13_reg_2602 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_14_reg_2607 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln708_s_reg_2612 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_fu_2193_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_reg_2617 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_56_fu_2198_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_56_reg_2622 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_57_fu_2203_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_57_reg_2627 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_58_fu_2208_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_58_reg_2632 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_59_fu_2213_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_59_reg_2637 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_60_fu_2218_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_60_reg_2642 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_61_fu_2223_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_61_reg_2647 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_62_fu_2228_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln703_62_reg_2652 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_cur_activ_reg_2657 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_cur_activ_1_reg_2662 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_cur_activ_2_reg_2667 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_cur_activ_3_reg_2672 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_cur_activ_4_reg_2677 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_cur_activ_5_reg_2682 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_cur_activ_6_reg_2687 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_cur_activ_7_reg_2692 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_hard_tanh_fu_1861_ap_ready : STD_LOGIC;
    signal call_ret_hard_tanh_fu_1861_data_0_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_hard_tanh_fu_1861_data_1_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_hard_tanh_fu_1861_data_2_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_hard_tanh_fu_1861_data_3_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_hard_tanh_fu_1861_data_4_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_hard_tanh_fu_1861_data_5_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_hard_tanh_fu_1861_data_6_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_hard_tanh_fu_1861_data_7_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_hard_tanh_fu_1861_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_hard_tanh_fu_1861_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_hard_tanh_fu_1861_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_hard_tanh_fu_1861_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_hard_tanh_fu_1861_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_hard_tanh_fu_1861_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_hard_tanh_fu_1861_ap_return_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret_hard_tanh_fu_1861_ap_return_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal mul_ln1118_8_fu_348_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_8_fu_348_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_1_fu_349_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_1_fu_349_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1118_9_fu_350_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_9_fu_350_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1118_12_fu_351_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_12_fu_351_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_14_fu_352_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_14_fu_352_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_19_fu_353_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_19_fu_353_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_3_fu_354_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_3_fu_354_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1118_11_fu_355_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_11_fu_355_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1118_23_fu_356_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_23_fu_356_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_2_fu_357_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_2_fu_357_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_6_fu_358_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_6_fu_358_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_21_fu_359_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_21_fu_359_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_13_fu_360_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_13_fu_360_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1118_4_fu_361_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_4_fu_361_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_15_fu_362_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_15_fu_362_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1118_22_fu_363_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_22_fu_363_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_7_fu_364_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_7_fu_364_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1118_10_fu_365_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_10_fu_365_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_17_fu_366_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_17_fu_366_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_20_fu_367_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_20_fu_367_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_5_fu_368_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_5_fu_368_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln1118_fu_369_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_fu_369_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_18_fu_370_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_18_fu_370_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_16_fu_371_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_16_fu_371_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1118_fu_369_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_1_fu_349_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_2_fu_357_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_3_fu_354_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_4_fu_361_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_5_fu_368_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_6_fu_358_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_7_fu_364_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_8_fu_348_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_9_fu_350_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_10_fu_365_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_11_fu_355_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_12_fu_351_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_13_fu_360_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_14_fu_352_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_15_fu_362_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_16_fu_371_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_17_fu_366_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_18_fu_370_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_19_fu_353_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_20_fu_367_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_21_fu_359_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_22_fu_363_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_23_fu_356_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal gate_i_0_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_i_1_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_i_2_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_i_3_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_i_4_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_i_5_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_i_6_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_i_7_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_f_0_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_f_1_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_f_2_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_f_3_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_f_4_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_f_5_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_f_6_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_f_7_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_g_0_V_read_int_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal gate_g_1_V_read_int_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal gate_g_2_V_read_int_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal gate_g_3_V_read_int_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal gate_g_4_V_read_int_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal gate_g_5_V_read_int_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal gate_g_6_V_read_int_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal gate_g_7_V_read_int_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal gate_o_0_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_1_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_2_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_3_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_4_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_5_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_6_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal gate_o_7_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal c_pre_0_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal c_pre_1_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal c_pre_2_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal c_pre_3_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal c_pre_4_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal c_pre_5_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal c_pre_6_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal c_pre_7_V_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_3_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_4_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_5_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_6_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_7_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_8_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_9_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_10_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_11_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_12_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_13_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_14_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_15_int_reg : STD_LOGIC_VECTOR (15 downto 0);

    component hard_tanh IS
    port (
        ap_ready : OUT STD_LOGIC;
        data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    call_ret_hard_tanh_fu_1861 : component hard_tanh
    port map (
        ap_ready => call_ret_hard_tanh_fu_1861_ap_ready,
        data_0_V_read => call_ret_hard_tanh_fu_1861_data_0_V_read,
        data_1_V_read => call_ret_hard_tanh_fu_1861_data_1_V_read,
        data_2_V_read => call_ret_hard_tanh_fu_1861_data_2_V_read,
        data_3_V_read => call_ret_hard_tanh_fu_1861_data_3_V_read,
        data_4_V_read => call_ret_hard_tanh_fu_1861_data_4_V_read,
        data_5_V_read => call_ret_hard_tanh_fu_1861_data_5_V_read,
        data_6_V_read => call_ret_hard_tanh_fu_1861_data_6_V_read,
        data_7_V_read => call_ret_hard_tanh_fu_1861_data_7_V_read,
        ap_return_0 => call_ret_hard_tanh_fu_1861_ap_return_0,
        ap_return_1 => call_ret_hard_tanh_fu_1861_ap_return_1,
        ap_return_2 => call_ret_hard_tanh_fu_1861_ap_return_2,
        ap_return_3 => call_ret_hard_tanh_fu_1861_ap_return_3,
        ap_return_4 => call_ret_hard_tanh_fu_1861_ap_return_4,
        ap_return_5 => call_ret_hard_tanh_fu_1861_ap_return_5,
        ap_return_6 => call_ret_hard_tanh_fu_1861_ap_return_6,
        ap_return_7 => call_ret_hard_tanh_fu_1861_ap_return_7);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                add_ln703_56_reg_2622 <= add_ln703_56_fu_2198_p2;
                add_ln703_57_reg_2627 <= add_ln703_57_fu_2203_p2;
                add_ln703_58_reg_2632 <= add_ln703_58_fu_2208_p2;
                add_ln703_59_reg_2637 <= add_ln703_59_fu_2213_p2;
                add_ln703_60_reg_2642 <= add_ln703_60_fu_2218_p2;
                add_ln703_61_reg_2647 <= add_ln703_61_fu_2223_p2;
                add_ln703_62_reg_2652 <= add_ln703_62_fu_2228_p2;
                add_ln703_reg_2617 <= add_ln703_fu_2193_p2;
                c_cur_activ_1_reg_2662 <= call_ret_hard_tanh_fu_1861_ap_return_1;
                c_cur_activ_2_reg_2667 <= call_ret_hard_tanh_fu_1861_ap_return_2;
                c_cur_activ_3_reg_2672 <= call_ret_hard_tanh_fu_1861_ap_return_3;
                c_cur_activ_4_reg_2677 <= call_ret_hard_tanh_fu_1861_ap_return_4;
                c_cur_activ_5_reg_2682 <= call_ret_hard_tanh_fu_1861_ap_return_5;
                c_cur_activ_6_reg_2687 <= call_ret_hard_tanh_fu_1861_ap_return_6;
                c_cur_activ_7_reg_2692 <= call_ret_hard_tanh_fu_1861_ap_return_7;
                c_cur_activ_reg_2657 <= call_ret_hard_tanh_fu_1861_ap_return_0;
                gate_o_0_V_read_2_reg_2532 <= gate_o_0_V_read_int_reg;
                gate_o_0_V_read_2_reg_2532_pp0_iter1_reg <= gate_o_0_V_read_2_reg_2532;
                gate_o_1_V_read_2_reg_2527 <= gate_o_1_V_read_int_reg;
                gate_o_1_V_read_2_reg_2527_pp0_iter1_reg <= gate_o_1_V_read_2_reg_2527;
                gate_o_2_V_read_2_reg_2522 <= gate_o_2_V_read_int_reg;
                gate_o_2_V_read_2_reg_2522_pp0_iter1_reg <= gate_o_2_V_read_2_reg_2522;
                gate_o_3_V_read_2_reg_2517 <= gate_o_3_V_read_int_reg;
                gate_o_3_V_read_2_reg_2517_pp0_iter1_reg <= gate_o_3_V_read_2_reg_2517;
                gate_o_4_V_read_2_reg_2512 <= gate_o_4_V_read_int_reg;
                gate_o_4_V_read_2_reg_2512_pp0_iter1_reg <= gate_o_4_V_read_2_reg_2512;
                gate_o_5_V_read_2_reg_2507 <= gate_o_5_V_read_int_reg;
                gate_o_5_V_read_2_reg_2507_pp0_iter1_reg <= gate_o_5_V_read_2_reg_2507;
                gate_o_6_V_read31_reg_2502 <= gate_o_6_V_read_int_reg;
                gate_o_6_V_read31_reg_2502_pp0_iter1_reg <= gate_o_6_V_read31_reg_2502;
                gate_o_7_V_read_2_reg_2497 <= gate_o_7_V_read_int_reg;
                gate_o_7_V_read_2_reg_2497_pp0_iter1_reg <= gate_o_7_V_read_2_reg_2497;
                trunc_ln708_10_reg_2587 <= mul_ln1118_10_fu_365_p2(25 downto 10);
                trunc_ln708_11_reg_2592 <= mul_ln1118_11_fu_355_p2(25 downto 10);
                trunc_ln708_12_reg_2597 <= mul_ln1118_12_fu_351_p2(25 downto 10);
                trunc_ln708_13_reg_2602 <= mul_ln1118_13_fu_360_p2(25 downto 10);
                trunc_ln708_14_reg_2607 <= mul_ln1118_14_fu_352_p2(25 downto 10);
                trunc_ln708_1_reg_2542 <= mul_ln1118_1_fu_349_p2(25 downto 10);
                trunc_ln708_2_reg_2547 <= mul_ln1118_2_fu_357_p2(25 downto 10);
                trunc_ln708_3_reg_2552 <= mul_ln1118_3_fu_354_p2(25 downto 10);
                trunc_ln708_4_reg_2557 <= mul_ln1118_4_fu_361_p2(25 downto 10);
                trunc_ln708_5_reg_2562 <= mul_ln1118_5_fu_368_p2(25 downto 10);
                trunc_ln708_6_reg_2567 <= mul_ln1118_6_fu_358_p2(25 downto 10);
                trunc_ln708_7_reg_2572 <= mul_ln1118_7_fu_364_p2(25 downto 10);
                trunc_ln708_8_reg_2577 <= mul_ln1118_8_fu_348_p2(25 downto 10);
                trunc_ln708_9_reg_2582 <= mul_ln1118_9_fu_350_p2(25 downto 10);
                trunc_ln708_s_reg_2612 <= mul_ln1118_15_fu_362_p2(25 downto 10);
                trunc_ln_reg_2537 <= mul_ln1118_fu_369_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= mul_ln1118_16_fu_371_p2(25 downto 10);
                ap_return_10_int_reg <= add_ln703_57_reg_2627;
                ap_return_11_int_reg <= add_ln703_58_reg_2632;
                ap_return_12_int_reg <= add_ln703_59_reg_2637;
                ap_return_13_int_reg <= add_ln703_60_reg_2642;
                ap_return_14_int_reg <= add_ln703_61_reg_2647;
                ap_return_15_int_reg <= add_ln703_62_reg_2652;
                ap_return_1_int_reg <= mul_ln1118_17_fu_366_p2(25 downto 10);
                ap_return_2_int_reg <= mul_ln1118_18_fu_370_p2(25 downto 10);
                ap_return_3_int_reg <= mul_ln1118_19_fu_353_p2(25 downto 10);
                ap_return_4_int_reg <= mul_ln1118_20_fu_367_p2(25 downto 10);
                ap_return_5_int_reg <= mul_ln1118_21_fu_359_p2(25 downto 10);
                ap_return_6_int_reg <= mul_ln1118_22_fu_363_p2(25 downto 10);
                ap_return_7_int_reg <= mul_ln1118_23_fu_356_p2(25 downto 10);
                ap_return_8_int_reg <= add_ln703_reg_2617;
                ap_return_9_int_reg <= add_ln703_56_reg_2622;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                c_pre_0_V_read_int_reg <= c_pre_0_V_read;
                c_pre_1_V_read_int_reg <= c_pre_1_V_read;
                c_pre_2_V_read_int_reg <= c_pre_2_V_read;
                c_pre_3_V_read_int_reg <= c_pre_3_V_read;
                c_pre_4_V_read_int_reg <= c_pre_4_V_read;
                c_pre_5_V_read_int_reg <= c_pre_5_V_read;
                c_pre_6_V_read_int_reg <= c_pre_6_V_read;
                c_pre_7_V_read_int_reg <= c_pre_7_V_read;
                gate_f_0_V_read_int_reg <= gate_f_0_V_read;
                gate_f_1_V_read_int_reg <= gate_f_1_V_read;
                gate_f_2_V_read_int_reg <= gate_f_2_V_read;
                gate_f_3_V_read_int_reg <= gate_f_3_V_read;
                gate_f_4_V_read_int_reg <= gate_f_4_V_read;
                gate_f_5_V_read_int_reg <= gate_f_5_V_read;
                gate_f_6_V_read_int_reg <= gate_f_6_V_read;
                gate_f_7_V_read_int_reg <= gate_f_7_V_read;
                gate_g_0_V_read_int_reg <= gate_g_0_V_read;
                gate_g_1_V_read_int_reg <= gate_g_1_V_read;
                gate_g_2_V_read_int_reg <= gate_g_2_V_read;
                gate_g_3_V_read_int_reg <= gate_g_3_V_read;
                gate_g_4_V_read_int_reg <= gate_g_4_V_read;
                gate_g_5_V_read_int_reg <= gate_g_5_V_read;
                gate_g_6_V_read_int_reg <= gate_g_6_V_read;
                gate_g_7_V_read_int_reg <= gate_g_7_V_read;
                gate_i_0_V_read_int_reg <= gate_i_0_V_read;
                gate_i_1_V_read_int_reg <= gate_i_1_V_read;
                gate_i_2_V_read_int_reg <= gate_i_2_V_read;
                gate_i_3_V_read_int_reg <= gate_i_3_V_read;
                gate_i_4_V_read_int_reg <= gate_i_4_V_read;
                gate_i_5_V_read_int_reg <= gate_i_5_V_read;
                gate_i_6_V_read_int_reg <= gate_i_6_V_read;
                gate_i_7_V_read_int_reg <= gate_i_7_V_read;
                gate_o_0_V_read_int_reg <= gate_o_0_V_read;
                gate_o_1_V_read_int_reg <= gate_o_1_V_read;
                gate_o_2_V_read_int_reg <= gate_o_2_V_read;
                gate_o_3_V_read_int_reg <= gate_o_3_V_read;
                gate_o_4_V_read_int_reg <= gate_o_4_V_read;
                gate_o_5_V_read_int_reg <= gate_o_5_V_read;
                gate_o_6_V_read_int_reg <= gate_o_6_V_read;
                gate_o_7_V_read_int_reg <= gate_o_7_V_read;
            end if;
        end if;
    end process;
    add_ln703_56_fu_2198_p2 <= std_logic_vector(unsigned(trunc_ln708_2_reg_2547) + unsigned(trunc_ln708_3_reg_2552));
    add_ln703_57_fu_2203_p2 <= std_logic_vector(unsigned(trunc_ln708_4_reg_2557) + unsigned(trunc_ln708_5_reg_2562));
    add_ln703_58_fu_2208_p2 <= std_logic_vector(unsigned(trunc_ln708_6_reg_2567) + unsigned(trunc_ln708_7_reg_2572));
    add_ln703_59_fu_2213_p2 <= std_logic_vector(unsigned(trunc_ln708_8_reg_2577) + unsigned(trunc_ln708_9_reg_2582));
    add_ln703_60_fu_2218_p2 <= std_logic_vector(unsigned(trunc_ln708_10_reg_2587) + unsigned(trunc_ln708_11_reg_2592));
    add_ln703_61_fu_2223_p2 <= std_logic_vector(unsigned(trunc_ln708_12_reg_2597) + unsigned(trunc_ln708_13_reg_2602));
    add_ln703_62_fu_2228_p2 <= std_logic_vector(unsigned(trunc_ln708_14_reg_2607) + unsigned(trunc_ln708_s_reg_2612));
    add_ln703_fu_2193_p2 <= std_logic_vector(unsigned(trunc_ln_reg_2537) + unsigned(trunc_ln708_1_reg_2542));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(mul_ln1118_16_fu_371_p2, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= mul_ln1118_16_fu_371_p2(25 downto 10);
        end if; 
    end process;


    ap_return_1_assign_proc : process(mul_ln1118_17_fu_366_p2, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= mul_ln1118_17_fu_366_p2(25 downto 10);
        end if; 
    end process;


    ap_return_10_assign_proc : process(add_ln703_57_reg_2627, ap_ce_reg, ap_return_10_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_10 <= ap_return_10_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_10 <= add_ln703_57_reg_2627;
        end if; 
    end process;


    ap_return_11_assign_proc : process(add_ln703_58_reg_2632, ap_ce_reg, ap_return_11_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_11 <= ap_return_11_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_11 <= add_ln703_58_reg_2632;
        end if; 
    end process;


    ap_return_12_assign_proc : process(add_ln703_59_reg_2637, ap_ce_reg, ap_return_12_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_12 <= ap_return_12_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_12 <= add_ln703_59_reg_2637;
        end if; 
    end process;


    ap_return_13_assign_proc : process(add_ln703_60_reg_2642, ap_ce_reg, ap_return_13_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_13 <= ap_return_13_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_13 <= add_ln703_60_reg_2642;
        end if; 
    end process;


    ap_return_14_assign_proc : process(add_ln703_61_reg_2647, ap_ce_reg, ap_return_14_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_14 <= ap_return_14_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_14 <= add_ln703_61_reg_2647;
        end if; 
    end process;


    ap_return_15_assign_proc : process(add_ln703_62_reg_2652, ap_ce_reg, ap_return_15_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_15 <= ap_return_15_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_15 <= add_ln703_62_reg_2652;
        end if; 
    end process;


    ap_return_2_assign_proc : process(mul_ln1118_18_fu_370_p2, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= mul_ln1118_18_fu_370_p2(25 downto 10);
        end if; 
    end process;


    ap_return_3_assign_proc : process(mul_ln1118_19_fu_353_p2, ap_ce_reg, ap_return_3_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_3 <= ap_return_3_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_3 <= mul_ln1118_19_fu_353_p2(25 downto 10);
        end if; 
    end process;


    ap_return_4_assign_proc : process(mul_ln1118_20_fu_367_p2, ap_ce_reg, ap_return_4_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_4 <= ap_return_4_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_4 <= mul_ln1118_20_fu_367_p2(25 downto 10);
        end if; 
    end process;


    ap_return_5_assign_proc : process(mul_ln1118_21_fu_359_p2, ap_ce_reg, ap_return_5_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_5 <= ap_return_5_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_5 <= mul_ln1118_21_fu_359_p2(25 downto 10);
        end if; 
    end process;


    ap_return_6_assign_proc : process(mul_ln1118_22_fu_363_p2, ap_ce_reg, ap_return_6_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_6 <= ap_return_6_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_6 <= mul_ln1118_22_fu_363_p2(25 downto 10);
        end if; 
    end process;


    ap_return_7_assign_proc : process(mul_ln1118_23_fu_356_p2, ap_ce_reg, ap_return_7_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_7 <= ap_return_7_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_7 <= mul_ln1118_23_fu_356_p2(25 downto 10);
        end if; 
    end process;


    ap_return_8_assign_proc : process(add_ln703_reg_2617, ap_ce_reg, ap_return_8_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_8 <= ap_return_8_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_8 <= add_ln703_reg_2617;
        end if; 
    end process;


    ap_return_9_assign_proc : process(add_ln703_56_reg_2622, ap_ce_reg, ap_return_9_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_9 <= ap_return_9_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_9 <= add_ln703_56_reg_2622;
        end if; 
    end process;

    call_ret_hard_tanh_fu_1861_data_0_V_read <= std_logic_vector(unsigned(trunc_ln_reg_2537) + unsigned(trunc_ln708_1_reg_2542));
    call_ret_hard_tanh_fu_1861_data_1_V_read <= std_logic_vector(unsigned(trunc_ln708_2_reg_2547) + unsigned(trunc_ln708_3_reg_2552));
    call_ret_hard_tanh_fu_1861_data_2_V_read <= std_logic_vector(unsigned(trunc_ln708_4_reg_2557) + unsigned(trunc_ln708_5_reg_2562));
    call_ret_hard_tanh_fu_1861_data_3_V_read <= std_logic_vector(unsigned(trunc_ln708_6_reg_2567) + unsigned(trunc_ln708_7_reg_2572));
    call_ret_hard_tanh_fu_1861_data_4_V_read <= std_logic_vector(unsigned(trunc_ln708_8_reg_2577) + unsigned(trunc_ln708_9_reg_2582));
    call_ret_hard_tanh_fu_1861_data_5_V_read <= std_logic_vector(unsigned(trunc_ln708_10_reg_2587) + unsigned(trunc_ln708_11_reg_2592));
    call_ret_hard_tanh_fu_1861_data_6_V_read <= std_logic_vector(unsigned(trunc_ln708_12_reg_2597) + unsigned(trunc_ln708_13_reg_2602));
    call_ret_hard_tanh_fu_1861_data_7_V_read <= std_logic_vector(unsigned(trunc_ln708_14_reg_2607) + unsigned(trunc_ln708_s_reg_2612));
    mul_ln1118_10_fu_365_p0 <= gate_f_5_V_read_int_reg;
    mul_ln1118_10_fu_365_p1 <= c_pre_5_V_read_int_reg;
    mul_ln1118_10_fu_365_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_10_fu_365_p0) * signed(mul_ln1118_10_fu_365_p1))), 26));
    mul_ln1118_11_fu_355_p0 <= gate_i_5_V_read_int_reg;
    mul_ln1118_11_fu_355_p1 <= gate_g_5_V_read_int_reg;
    mul_ln1118_11_fu_355_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_11_fu_355_p0) * signed(mul_ln1118_11_fu_355_p1))), 26));
    mul_ln1118_12_fu_351_p0 <= gate_f_6_V_read_int_reg;
    mul_ln1118_12_fu_351_p1 <= c_pre_6_V_read_int_reg;
    mul_ln1118_12_fu_351_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_12_fu_351_p0) * signed(mul_ln1118_12_fu_351_p1))), 26));
    mul_ln1118_13_fu_360_p0 <= gate_i_6_V_read_int_reg;
    mul_ln1118_13_fu_360_p1 <= gate_g_6_V_read_int_reg;
    mul_ln1118_13_fu_360_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_13_fu_360_p0) * signed(mul_ln1118_13_fu_360_p1))), 26));
    mul_ln1118_14_fu_352_p0 <= gate_f_7_V_read_int_reg;
    mul_ln1118_14_fu_352_p1 <= c_pre_7_V_read_int_reg;
    mul_ln1118_14_fu_352_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_14_fu_352_p0) * signed(mul_ln1118_14_fu_352_p1))), 26));
    mul_ln1118_15_fu_362_p0 <= gate_i_7_V_read_int_reg;
    mul_ln1118_15_fu_362_p1 <= gate_g_7_V_read_int_reg;
    mul_ln1118_15_fu_362_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_15_fu_362_p0) * signed(mul_ln1118_15_fu_362_p1))), 26));
    mul_ln1118_16_fu_371_p0 <= gate_o_0_V_read_2_reg_2532_pp0_iter1_reg;
    mul_ln1118_16_fu_371_p1 <= c_cur_activ_reg_2657;
    mul_ln1118_16_fu_371_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_16_fu_371_p0) * signed(mul_ln1118_16_fu_371_p1))), 26));
    mul_ln1118_17_fu_366_p0 <= gate_o_1_V_read_2_reg_2527_pp0_iter1_reg;
    mul_ln1118_17_fu_366_p1 <= c_cur_activ_1_reg_2662;
    mul_ln1118_17_fu_366_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_17_fu_366_p0) * signed(mul_ln1118_17_fu_366_p1))), 26));
    mul_ln1118_18_fu_370_p0 <= gate_o_2_V_read_2_reg_2522_pp0_iter1_reg;
    mul_ln1118_18_fu_370_p1 <= c_cur_activ_2_reg_2667;
    mul_ln1118_18_fu_370_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_18_fu_370_p0) * signed(mul_ln1118_18_fu_370_p1))), 26));
    mul_ln1118_19_fu_353_p0 <= gate_o_3_V_read_2_reg_2517_pp0_iter1_reg;
    mul_ln1118_19_fu_353_p1 <= c_cur_activ_3_reg_2672;
    mul_ln1118_19_fu_353_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_19_fu_353_p0) * signed(mul_ln1118_19_fu_353_p1))), 26));
    mul_ln1118_1_fu_349_p0 <= gate_i_0_V_read_int_reg;
    mul_ln1118_1_fu_349_p1 <= gate_g_0_V_read_int_reg;
    mul_ln1118_1_fu_349_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_1_fu_349_p0) * signed(mul_ln1118_1_fu_349_p1))), 26));
    mul_ln1118_20_fu_367_p0 <= gate_o_4_V_read_2_reg_2512_pp0_iter1_reg;
    mul_ln1118_20_fu_367_p1 <= c_cur_activ_4_reg_2677;
    mul_ln1118_20_fu_367_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_20_fu_367_p0) * signed(mul_ln1118_20_fu_367_p1))), 26));
    mul_ln1118_21_fu_359_p0 <= gate_o_5_V_read_2_reg_2507_pp0_iter1_reg;
    mul_ln1118_21_fu_359_p1 <= c_cur_activ_5_reg_2682;
    mul_ln1118_21_fu_359_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_21_fu_359_p0) * signed(mul_ln1118_21_fu_359_p1))), 26));
    mul_ln1118_22_fu_363_p0 <= gate_o_6_V_read31_reg_2502_pp0_iter1_reg;
    mul_ln1118_22_fu_363_p1 <= c_cur_activ_6_reg_2687;
    mul_ln1118_22_fu_363_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_22_fu_363_p0) * signed(mul_ln1118_22_fu_363_p1))), 26));
    mul_ln1118_23_fu_356_p0 <= gate_o_7_V_read_2_reg_2497_pp0_iter1_reg;
    mul_ln1118_23_fu_356_p1 <= c_cur_activ_7_reg_2692;
    mul_ln1118_23_fu_356_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_23_fu_356_p0) * signed(mul_ln1118_23_fu_356_p1))), 26));
    mul_ln1118_2_fu_357_p0 <= gate_f_1_V_read_int_reg;
    mul_ln1118_2_fu_357_p1 <= c_pre_1_V_read_int_reg;
    mul_ln1118_2_fu_357_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_2_fu_357_p0) * signed(mul_ln1118_2_fu_357_p1))), 26));
    mul_ln1118_3_fu_354_p0 <= gate_i_1_V_read_int_reg;
    mul_ln1118_3_fu_354_p1 <= gate_g_1_V_read_int_reg;
    mul_ln1118_3_fu_354_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_3_fu_354_p0) * signed(mul_ln1118_3_fu_354_p1))), 26));
    mul_ln1118_4_fu_361_p0 <= gate_f_2_V_read_int_reg;
    mul_ln1118_4_fu_361_p1 <= c_pre_2_V_read_int_reg;
    mul_ln1118_4_fu_361_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_4_fu_361_p0) * signed(mul_ln1118_4_fu_361_p1))), 26));
    mul_ln1118_5_fu_368_p0 <= gate_i_2_V_read_int_reg;
    mul_ln1118_5_fu_368_p1 <= gate_g_2_V_read_int_reg;
    mul_ln1118_5_fu_368_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_5_fu_368_p0) * signed(mul_ln1118_5_fu_368_p1))), 26));
    mul_ln1118_6_fu_358_p0 <= gate_f_3_V_read_int_reg;
    mul_ln1118_6_fu_358_p1 <= c_pre_3_V_read_int_reg;
    mul_ln1118_6_fu_358_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_6_fu_358_p0) * signed(mul_ln1118_6_fu_358_p1))), 26));
    mul_ln1118_7_fu_364_p0 <= gate_i_3_V_read_int_reg;
    mul_ln1118_7_fu_364_p1 <= gate_g_3_V_read_int_reg;
    mul_ln1118_7_fu_364_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_7_fu_364_p0) * signed(mul_ln1118_7_fu_364_p1))), 26));
    mul_ln1118_8_fu_348_p0 <= gate_f_4_V_read_int_reg;
    mul_ln1118_8_fu_348_p1 <= c_pre_4_V_read_int_reg;
    mul_ln1118_8_fu_348_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_8_fu_348_p0) * signed(mul_ln1118_8_fu_348_p1))), 26));
    mul_ln1118_9_fu_350_p0 <= gate_i_4_V_read_int_reg;
    mul_ln1118_9_fu_350_p1 <= gate_g_4_V_read_int_reg;
    mul_ln1118_9_fu_350_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_9_fu_350_p0) * signed(mul_ln1118_9_fu_350_p1))), 26));
    mul_ln1118_fu_369_p0 <= gate_f_0_V_read_int_reg;
    mul_ln1118_fu_369_p1 <= c_pre_0_V_read_int_reg;
    mul_ln1118_fu_369_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln1118_fu_369_p0) * signed(mul_ln1118_fu_369_p1))), 26));
end behav;
