-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tanh is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (10 downto 0) );
end;


architecture behav of tanh is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv26_3FFFFF9 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111111111001";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv14_200 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_const_lv13_200 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tanh_table9_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal tanh_table9_ce0 : STD_LOGIC;
    signal tanh_table9_q0 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln322_fu_181_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln322_reg_212 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln323_fu_195_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln323_reg_217 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln324_fu_207_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_fu_89_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_fu_81_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln851_fu_109_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Result_2_fu_113_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln835_fu_99_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln851_fu_121_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_fu_127_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_Result_s_fu_103_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_fu_133_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln850_fu_141_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln320_fu_149_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal index_fu_153_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_2_fu_165_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln320_1_fu_159_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln322_fu_173_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_3_fu_185_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln323_fu_201_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component tanh_tanh_table9 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;



begin
    tanh_table9_U : component tanh_tanh_table9
    generic map (
        DataWidth => 11,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tanh_table9_address0,
        ce0 => tanh_table9_ce0,
        q0 => tanh_table9_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln323_reg_217 <= icmp_ln323_fu_195_p2;
                trunc_ln322_reg_212 <= trunc_ln322_fu_181_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln320_1_fu_159_p2 <= std_logic_vector(unsigned(ap_const_lv13_200) + unsigned(trunc_ln320_fu_149_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= tanh_table9_q0;
    icmp_ln323_fu_195_p2 <= "0" when (tmp_3_fu_185_p4 = ap_const_lv3_0) else "1";
    icmp_ln851_fu_121_p2 <= "1" when (p_Result_2_fu_113_p3 = ap_const_lv10_0) else "0";
    index_fu_153_p2 <= std_logic_vector(unsigned(ap_const_lv14_200) + unsigned(select_ln850_fu_141_p3));
    p_Result_2_fu_113_p3 <= (trunc_ln851_fu_109_p1 & ap_const_lv7_0);
    p_Result_s_fu_103_p2 <= "1" when (signed(r_V_fu_81_p3) < signed(ap_const_lv26_3FFFFF9)) else "0";
    r_V_fu_81_p3 <= (data_V_read & ap_const_lv10_0);
    ret_V_fu_127_p2 <= std_logic_vector(unsigned(ap_const_lv14_1) + unsigned(sext_ln835_fu_99_p1));
    select_ln322_fu_173_p3 <= 
        ap_const_lv13_0 when (tmp_2_fu_165_p3(0) = '1') else 
        add_ln320_1_fu_159_p2;
    select_ln323_fu_201_p3 <= 
        ap_const_lv10_3FF when (icmp_ln323_reg_217(0) = '1') else 
        trunc_ln322_reg_212;
    select_ln850_fu_141_p3 <= 
        select_ln851_fu_133_p3 when (p_Result_s_fu_103_p2(0) = '1') else 
        sext_ln835_fu_99_p1;
    select_ln851_fu_133_p3 <= 
        sext_ln835_fu_99_p1 when (icmp_ln851_fu_121_p2(0) = '1') else 
        ret_V_fu_127_p2;
        sext_ln835_fu_99_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_89_p4),14));

    tanh_table9_address0 <= zext_ln324_fu_207_p1(10 - 1 downto 0);

    tanh_table9_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tanh_table9_ce0 <= ap_const_logic_1;
        else 
            tanh_table9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_89_p4 <= data_V_read(15 downto 3);
    tmp_2_fu_165_p3 <= index_fu_153_p2(13 downto 13);
    tmp_3_fu_185_p4 <= select_ln322_fu_173_p3(12 downto 10);
    trunc_ln320_fu_149_p1 <= select_ln850_fu_141_p3(13 - 1 downto 0);
    trunc_ln322_fu_181_p1 <= select_ln322_fu_173_p3(10 - 1 downto 0);
    trunc_ln851_fu_109_p1 <= data_V_read(3 - 1 downto 0);
    zext_ln324_fu_207_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln323_fu_201_p3),64));
end behav;
